// Run: node tests/engine.cjs (or Get-Content tests/engine.cjs -Raw | node).
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
for(const f of ['catalog.js','game.js'])vm.runInThisContext(fs.readFileSync('src/'+f,'utf8'),{filename:f});
let passed=0;function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){console.error('FAIL '+name);throw e;}}
function arena(role='Valkyrie'){const g=new NH.Game('test',role);g.level.monsters=[];g.level.items=[];g.level.traps=[];g.level.boulders=[];g.level.rooms=[];for(let t of g.level.tiles.flat()){t.type=t.x>=2&&t.x<=10&&t.y>=2&&t.y<=10?'floor':'wall';t.seen=false;}g.player.x=5;g.player.y=5;g.updateVision();return g;}
test('Reference catalog includes all 381 standard monster records',()=>{assert.equal(NH.MONSTERS.length,381);assert.equal(new Set(NH.MONSTERS.map(m=>m.name+":"+m.family)).size,381);assert.equal(NH.monsterDef('goblin').ac,10);assert.equal(NH.monsterDef('killer bee').speed,18);assert.equal(NH.lookup('food ration','food').nutrition,800);assert.equal(NH.lookup('gray dragon scale mail','armor').ac,9);assert.equal(NH.lookup('force bolt','spellbook').level,1);});
test('Every role starts with resolvable objects and finite stats',()=>{for(let role of Object.keys(NH.roles)){let g=new NH.Game('role',role);assert.equal(g.player.role,role);assert.ok(Number.isFinite(g.ac));assert.ok(g.player.hp>0);for(let i of g.player.inventory)assert.ok(NH.lookup(i.name,i.category),role+': '+i.name);}});
test('Seed reproduces dungeon, inventory, creatures, and item appearances',()=>{let a=new NH.Game('repro'),b=new NH.Game('repro');assert.equal(a.serialize(),b.serialize());assert.notEqual(a.serialize(),new NH.Game('different').serialize());});
test('100 seeded dungeons connect all rooms and both staircases',()=>{for(let n=0;n<100;n++){let g=new NH.Game(n);let l=g.level,queue=[l.up],seen=new Set([l.up.x+','+l.up.y]);for(let i=0;i<queue.length;i++){let p=queue[i];for(let [dx,dy]of [[0,1],[0,-1],[1,0],[-1,0]]){let x=p.x+dx,y=p.y+dy,t=l.tiles[y]?.[x],k=x+','+y;if(!t||['wall','rock'].includes(t.type)||seen.has(k))continue;seen.add(k);queue.push({x,y});}}assert.ok(seen.has(l.down.x+','+l.down.y),'stairs, seed '+n);for(let r of l.rooms)assert.ok(seen.has((r.x+1)+','+(r.y+1)),'room, seed '+n);assert.ok(l.rooms.length>=4);}});
test('Walking consumes exactly one turn; blocked movement consumes none',()=>{let g=arena();assert.ok(g.move(1,0));assert.equal(g.turn,2);g.tile(7,5).type='wall';assert.equal(g.move(1,0),false);assert.equal(g.turn,2);});
test('Eight directions move to the expected square',()=>{for(let [dx,dy]of NH.DIRS){let g=arena();g.move(dx,dy);assert.equal(g.player.x,5+dx);assert.equal(g.player.y,5+dy);}});
test('Diagonal doorways and blocked corners prevent movement',()=>{let g=arena();g.tile(6,6).type='openDoor';assert.equal(g.move(1,1),false);g.tile(6,6).type='floor';g.tile(6,5).type='wall';g.tile(5,6).type='wall';assert.equal(g.move(1,1),false);});
test('Pet swaps places, remains tame, and advances a turn',()=>{let g=arena();let pet=g.spawn('little dog',6,5,{tame:true,name:'Hachi'});g.move(1,0);assert.equal(g.player.x,6);assert.equal(pet.x,5);assert.equal(pet.tame,true);assert.equal(g.turn,2);});
test('Hostile bump attacks instead of moving onto its square',()=>{let g=arena();let m=g.spawn('goblin',6,5,{hp:100,maxHp:100});g.move(1,0);assert.equal(g.player.x,5);assert.equal(g.turn,2);assert.ok(m.hp<100);});
test('Peaceful creatures are protected from normal bump attacks',()=>{let g=arena();let m=g.spawn('shopkeeper',6,5,{peaceful:true});let hp=m.hp;assert.equal(g.move(1,0),false);assert.equal(m.hp,hp);assert.equal(g.turn,1);});
test('Opening, closing, and unlocking update movement and visibility',()=>{let g=arena();g.tile(6,5).type='door';g.tile(6,5).locked=true;g.door(1,0);assert.equal(g.tile(6,5).type,'door');g.door(1,0,'unlock');g.door(1,0);assert.equal(g.tile(6,5).type,'openDoor');assert.ok(g.passable(6,5));g.door(1,0,'close');assert.equal(g.tile(6,5).type,'door');});
test('Boulders push cardinally and fill pits',()=>{let g=arena();g.level.boulders.push({id:1000,x:6,y:5});g.level.traps.push({x:7,y:5,type:'pit',seen:true});assert.ok(g.move(1,0));assert.equal(g.level.boulders.length,0);assert.equal(g.level.traps.length,0);assert.equal(g.player.x,6);});
test('Gold autopickup and manual object pickup have distinct behavior',()=>{let g=arena();g.level.items.push({x:6,y:5,item:g.createItem('gold piece','gold',{count:13})},{x:6,y:5,item:g.createItem('healing','potion')});g.move(1,0);assert.equal(g.player.gold,13);assert.equal(g.level.items.length,1);assert.equal(g.turn,2);g.pickup();assert.equal(g.level.items.length,0);assert.ok(g.player.inventory.some(i=>i.name==='healing'));assert.equal(g.turn,3);});
test('Inventory letters are unique after stack, drop, and pickup',()=>{let g=arena();for(let n=0;n<10;n++)g.addItem(g.createItem('healing','potion',{known:false,buc:0}));let pots=g.player.inventory.filter(i=>i.name==='healing');assert.equal(pots.length,1);assert.equal(pots[0].count,10);g.drop(pots[0]);g.pickup();let letters=g.player.inventory.map(i=>i.letter);assert.equal(new Set(letters).size,letters.length);});
test('Armor protection applies only once and only while worn',()=>{let g=arena();assert.equal(g.ac,6);let i=g.player.inventory.find(i=>i.category==='armor');g.player.equipment.quiver=i.id;assert.equal(g.ac,6);g.unequip(i);assert.equal(g.ac,10);g.player.equipment.weapon=i.id;assert.equal(g.ac,10);});
test('Cursed worn armor cannot be removed, curse is revealed',()=>{let g=arena(),i=g.player.inventory.find(i=>i.category==='armor');i.buc=-1;i.bucKnown=false;assert.equal(g.unequip(i),false);assert.equal(i.bucKnown,true);assert.equal(g.ac,6);});
test('Resistance from worn items disappears on removal',()=>{let g=arena('Wizard');assert.ok(g.has('magic resistance'));let cloak=g.player.inventory.find(i=>i.name==='cloak of magic resistance');g.unequip(cloak);assert.equal(g.has('magic resistance'),false);});
test('Hunger thresholds and eating restore nutrition across multiple turns',()=>{let g=arena();g.player.nutrition=140;assert.equal(g.hunger,'Hungry');let ration=g.player.inventory.find(i=>i.category==='food');g.eat(ration);assert.equal(g.hunger,'Not hungry');assert.equal(g.player.nutrition,935);assert.equal(g.turn,6);});
test('Blindness restricts sight and blocks reading without consuming items',()=>{let g=arena();let i=g.createItem('identify','scroll');g.addItem(i);g.player.status.blindness=10;g.updateVision();assert.equal(g.tile(8,5).visible,false);assert.equal(g.read(i),false);assert.equal(i.count,1);assert.equal(g.turn,1);});
test('Healing potion heals, consumes, and identifies its appearance',()=>{let g=arena();g.player.hp=2;let i=g.createItem('healing','potion');g.addItem(i);g.quaff(i);assert.ok(g.player.hp>2);assert.ok(g.identified['potion:healing']);assert.ok(!g.player.inventory.includes(i));});
test('Water remains clear and does not duplicate randomized potion appearances',()=>{let g=arena();assert.equal(g.appearances['potion:water'],'clear');let values=Object.entries(g.appearances).filter(([k])=>k.startsWith('potion:')).map(([,v])=>v);assert.equal(new Set(values).size,values.length);});
test('Spell cost, knowledge and insufficient-power checks',()=>{let g=arena('Wizard'),s=g.player.spells[0];g.player.pw=4;assert.equal(g.cast(s,[1,0]),false);assert.equal(g.turn,1);g.player.pw=8;g.cast(s,[1,0]);assert.equal(g.player.pw,3);assert.equal(g.turn,2);assert.equal(s.knowledge,19999);});
test('Wand rays stop force bolts at walls and consume charges',()=>{let g=arena();let m=g.spawn('goblin',8,5,{hp:30,maxHp:30}),i=g.createItem('striking','wand',{charges:2});g.tile(7,5).type='wall';g.zap(i,[1,0]);assert.equal(i.charges,1);assert.equal(m.hp,30);});
test('Pit trap applies damage and immobilization',()=>{let g=arena();g.level.traps.push({x:6,y:5,type:'pit',seen:false});g.move(1,0);assert.ok(g.player.hp<16);assert.equal(g.level.traps[0].seen,true);assert.ok(g.player.status.trapped>0);let x=g.player.x;g.move(1,0);assert.equal(g.player.x,x);});
test('Search can reveal adjacent secret doors and hidden traps',()=>{let g=arena();g.tile(6,5).type='secret';g.level.traps.push({x:5,y:6,type:'pit',seen:false});for(let n=0;n<100;n++)g.search();assert.equal(g.tile(6,5).type,'door');assert.equal(g.level.traps[0].seen,true);});
test('Life saving consumes the worn amulet and prevents death',()=>{let g=arena(),i=g.createItem('amulet of life saving','amulet');g.addItem(i);g.equip(i);g.damage(100,'test');assert.equal(g.dead,false);assert.equal(g.player.hp,g.player.maxHp);assert.ok(!g.player.inventory.includes(i));});
test('Save restoration preserves RNG and future simulation exactly',()=>{let a=arena();a.move(1,0);let b=NH.Game.restore(a.serialize());for(let n=0;n<30;n++){a.wait();b.wait();}assert.equal(a.serialize(),b.serialize());});
test('Main dungeon stair return preserves previous level and correct stair',()=>{let g=new NH.Game('stairs');g.depth=3;g.getLevel();g.player.x=g.level.down.x;g.player.y=g.level.down.y;g.level.monsters=[];let key=g.key,down={...g.level.down};g.level.engravings['test']='persistent';g.stairs(1);assert.equal(g.depth,4);g.level.monsters=[];g.stairs(-1);assert.equal(g.key,key);assert.equal(g.level.engravings.test,'persistent');assert.equal(g.player.x,down.x);assert.equal(g.player.y,down.y);});
test('Mines branch entrance returns to the branch stair',()=>{let g=new NH.Game('mines');g.depth=3;g.getLevel();let stair={...g.level.branchStair};g.player.x=stair.x;g.player.y=stair.y;g.level.monsters=[];g.stairs(1);assert.equal(g.branch,'Mines');assert.equal(g.depth,1);g.level.monsters=[];g.stairs(-1);assert.equal(g.branch,'Dungeons');assert.equal(g.depth,3);assert.equal(g.player.x,stair.x);assert.equal(g.player.y,stair.y);});
test('Invalid saves fail explicitly',()=>{assert.throws(()=>NH.Game.restore('{}'),/Incompatible/);assert.throws(()=>NH.Game.restore('{'));});
test('10,000 varied actions retain finite stats and valid positions',()=>{for(let n=0;n<20;n++){let g=new NH.Game('fuzz-'+n,'Wizard');g.player.hp=g.player.maxHp=10000;g.player.nutrition=5000;let r=new NH.RNG(n);for(let i=0;i<500&&!g.dead;i++){let action=r.int(0,10);if(action<8)g.move(...NH.DIRS[action]);else if(action===8)g.search();else g.wait();assert.ok(Number.isFinite(g.player.hp));assert.ok(Number.isFinite(g.ac));assert.ok(g.tile(g.player.x,g.player.y));assert.ok(g.player.pw>=0);}}});
console.log(`\n${passed} engine checks passed.`);
