const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
for(const f of ['catalog.js','world.js','game.js','systems.js','interactions.js','quests.js','drops.js','corpses.js','equipment.js','save-validation.js'])vm.runInThisContext(fs.readFileSync('src/'+f,'utf8'),{filename:f});
let passed=0;function test(name,fn){fn();console.log('PASS '+name);passed++;}
function arena(role='Valkyrie'){const g=new NH.Game('integration',role);g.level.monsters=[];g.level.items=[];g.level.boulders=[];g.level.traps=[];g.level.rooms=[];g.level.shops=[];for(const t of g.level.tiles.flat())t.type=t.x>1&&t.x<15&&t.y>1&&t.y<15?'floor':'wall';g.player.x=5;g.player.y=5;return g;}
function peaceful(g){g.level.monsters=[];g.player.hp=g.player.maxHp=10000;g.player.nutrition=10000;}
function shopGame(){let g=new NH.Game('shop-bill');g.depth=2;g.getLevel();const s=g.level.shops[0];assert.ok(s);g.level.monsters=g.level.monsters.filter(m=>m.shopkeeper);g.player.x=s.home.x;g.player.y=s.home.y+1;const r=g.level.rooms.find(r=>r.id===s.room);g.player.x=r.cx;g.player.y=r.cy;return {g,s};}
test('All valid race, role, and alignment combinations restore without gender state',()=>{for(const role of Object.keys(NH.roles))for(const race of NH.roleChoices[role])for(const align of NH.characterAlignments(role,race)){const a=new NH.Game(role+race,role,'Morgan',{race,align}),b=NH.Game.restore(a.serialize());assert.equal(b.player.race,race);assert.equal(b.player.align,align);assert.equal('gender' in b.player,false);assert.equal('orientation' in b.player,false);assert.deepEqual(a.player.stats,b.player.stats);}});
test('Character identity choices do not change combat balance',()=>{let a=new NH.Game('identity','Wizard','A',{align:'Neutral'}),b=new NH.Game('identity','Wizard','B',{align:'Neutral'});for(const key of ['hp','pw','maxHp','stats','align'])assert.deepEqual(a.player[key],b.player[key]);assert.equal('gender' in a.player,false);});
test('Invalid role-race combinations are rejected before generation',()=>assert.throws(()=>new NH.Game('x','Knight','x',{race:'Orc'}),/race/));
test('300 dungeons: doors sit between walls, corridors contain no 2x2 patches, and spawns never overlap',()=>{let altars=0,rooms=0;for(let seed=0;seed<300;seed++){let g=new NH.Game('architecture-'+seed),l=g.level;rooms+=l.rooms.length;for(let y=1;y<20;y++)for(let x=1;x<79;x++){let t=l.tiles[y][x];if(['door','openDoor','secret'].includes(t.type)){const sides=t.axis==='x'?[[0,1],[0,-1]]:[[1,0],[-1,0]];for(const [dx,dy]of sides)assert.equal(l.tiles[y+dy][x+dx].type,'wall',seed+': doorway lacks wall jamb');}if(t.type==='corridor')assert.ok(![l.tiles[y][x+1],l.tiles[y+1][x],l.tiles[y+1][x+1]].every(t=>t.type==='corridor'),'wide tunnel');if(t.type==='altar'){altars++;assert.ok(['Lawful','Neutral','Chaotic'].includes(t.align));assert.ok(Number.isInteger(t.facing));}}const occupied=l.monsters.map(m=>m.x+','+m.y);assert.equal(new Set(occupied).size,occupied.length);assert.ok(!l.monsters.some(m=>NH.distance(m,l.up)===0));}assert.ok(altars/rooms>.007&&altars/rooms<.03,`altar rate ${altars}/${rooms}`);});
test('Every branch and themed area generates with valid content and survives import',()=>{const g=new NH.Game('all-areas');for(const [branch,data]of Object.entries(NH.branches))for(let depth=1;depth<=data.max;depth++){g.branch=branch;g.depth=depth;g.getLevel();g.player.x=g.level.up.x;g.player.y=g.level.up.y;assert.ok(NH.themes[g.level.theme]);for(const o of g.level.items)assert.ok(NH.lookup(o.item.name,o.item.category));}NH.Game.restore(g.serialize());});
test('Shopkeepers move to block an unpaid exit and step aside after payment',()=>{const {g,s}=shopGame(),i=g.createItem('healing','potion',{unpaid:true,shopId:s.id,price:50,buc:0});g.addItem(i);g.endTurn();const keeper=g.findShop(s.id).keeper;assert.equal(NH.distance(keeper,s.entrance),0);g.player.x=s.entrance.x;g.player.y=s.entrance.y;keeper.x=s.home.x;keeper.y=s.home.y;const dx=s.door.x-s.entrance.x,dy=s.door.y-s.entrance.y;assert.equal(g.move(dx,dy),false);g.player.gold=100;assert.ok(g.pay());assert.equal(g.shopDebt(s),0);assert.equal(i.unpaid,false);assert.ok(g.move(dx,dy));});
test('Monster drops include the one-in-six object roll and special trophies',()=>{const g=arena();g.level.monsters=[];g.level.items=[];g.rng.int=(a,b)=>b===6?1:a;for(const name of ['red dragon','white unicorn']){const m=g.spawn(name,7,5,{hp:1,maxHp:1});g.kill(m);}assert.ok(g.level.items.some(o=>o.item.name==='red dragon scales'));assert.ok(g.level.items.some(o=>o.item.name==='unicorn horn'));});
test('Corpse intrinsics and restorative species effects apply once',()=>{const g=arena('Wizard');g.rng.next=()=>0;g.player.nutrition=0;let elf=g.createItem('corpse','food',{corpse:'elf',age:g.turn,known:true,nutrition:350});g.addItem(elf);g.eat(elf);assert.ok(g.player.properties.includes('MR_SLEEP'));let lizard=g.createItem('corpse','food',{corpse:'lizard',age:g.turn,known:true,nutrition:40});g.addItem(lizard);g.player.status.confusion=3;g.eat(lizard);assert.equal(g.player.status.confusion,undefined);let newt=g.createItem('corpse','food',{corpse:'newt',age:g.turn,known:true,nutrition:20});g.addItem(newt);const pw=g.player.pw;g.eat(newt);assert.ok(g.player.pw>=pw);});
test('Consumed unpaid merchandise remains on the bill after save/restore',()=>{const {g,s}=shopGame(),i=g.createItem('healing','potion',{unpaid:true,shopId:s.id,price:40,buc:0});g.addItem(i);g.quaff(i);assert.equal(g.shopDebt(s),40);const h=NH.Game.restore(g.serialize());assert.equal(h.shopDebt(h.level.shops[0]),40);});
test('Bag storage keeps merchandise on the bill and its contents persistent',()=>{const {g,s}=shopGame(),bag=g.createItem('bag of holding','tool',{buc:1}),i=g.createItem('healing','potion',{unpaid:true,shopId:s.id,price:35,buc:0,count:2});g.addItem(bag);g.addItem(i);g.storeItem(bag,i);assert.equal(g.shopDebt(s),70);const h=NH.Game.restore(g.serialize());assert.equal(h.allInventory().find(j=>j.name==='bag of holding').contents.length,1);assert.equal(h.shopDebt(h.level.shops[0]),70);});
test('Returning unpaid goods removes only their live balance',()=>{const {g,s}=shopGame(),i=g.createItem('healing','potion',{unpaid:true,shopId:s.id,price:35,buc:0});g.addItem(i);s.debit=17;g.drop(i);assert.equal(g.shopDebt(s),17);});
test('Blessed, uncursed and cursed bags have the expected weight multipliers',()=>{let g=arena(),bag=g.createItem('bag of holding','tool',{buc:1}),ration=g.createItem('food ration','food',{count:4,buc:0});bag.contents=[ration];assert.equal(g.itemWeight(bag),15+Math.ceil(4*20/4));bag.buc=0;assert.equal(g.itemWeight(bag),15+40);bag.buc=-1;assert.equal(g.itemWeight(bag),15+160);});
test('Inventory transfer conserves item counts and prevents container cycles',()=>{let g=arena(),a=g.createItem('sack','tool',{buc:0}),b=g.createItem('sack','tool',{buc:0});g.addItem(a);g.addItem(b);assert.equal(g.storeItem(a,a),false);assert.ok(g.storeItem(a,b));assert.equal(g.storeItem(b,a),false);assert.ok(g.takeItem(a,b));assert.equal(g.allInventory().filter(i=>i.id===b.id).length,1);});
test('Hunger and load warnings occur on transitions without repeating every turn',()=>{let g=arena();g.player.nutrition=151;g.conditionState={hunger:g.hunger,burden:g.encumbrance,lowHP:false};g.wait();assert.equal(g.alerts.filter(a=>a.kind==='hunger').length,1);g.wait();assert.equal(g.alerts.filter(a=>a.kind==='hunger').length,1);g.addItem(g.createItem('plate mail','armor',{count:5}));g.wait();assert.ok(g.alerts.some(a=>a.kind==='burden'));});
test('Encumbrance boundaries match the documented categories',()=>{const g=arena();g.player.inventory=[];g.player.gold=0;Object.defineProperty(g,'capacity',{value:100});for(const [weight,expected]of [[100,''],[101,'Burdened'],[149,'Burdened'],[150,'Stressed'],[200,'Strained'],[250,'Overtaxed'],[300,'Overloaded']]){Object.defineProperty(g,'weight',{value:weight,configurable:true});assert.equal(g.encumbrance,expected);}});
test('Non-damaging utility rays never damage their target or create random doors',()=>{for(const name of ['opening','locking','probing','cancellation','make invisible','speed monster','slow monster','nothing']){const g=arena(),m=g.spawn('goblin',7,5,{hp:40,maxHp:40});g.ray(name,[1,0],'wand');assert.equal(m.hp,40,name);assert.equal(g.tile(7,5).type,'floor',name);}});
test('Healing rays heal monsters and death rays respect undead immunity',()=>{let g=arena(),m=g.spawn('human zombie',7,5,{hp:40,maxHp:40});g.ray('death',[1,0],'wand');assert.equal(m.hp,40);m.hp=2;g.ray('healing',[1,0],'spell');assert.ok(m.hp>2);});
test('Thrown arrows are conserved and shattering potions are consumed',()=>{let g=arena(),a=g.createItem('arrow','weapon',{count:3,buc:0});g.addItem(a);g.throwItem(a,[1,0]);assert.equal(a.count,2);assert.equal(g.level.items.find(o=>o.item.name==='arrow').item.count,1);let potion=g.createItem('healing','potion',{buc:0});g.addItem(potion);g.throwItem(potion,[1,0]);assert.ok(!g.player.inventory.includes(potion));assert.ok(!g.level.items.some(o=>o.item.category==='potion'));});
test('Cursed weapons cannot be bypassed by throwing or swapping',()=>{const g=arena(),w=g.player.inventory.find(i=>i.id===g.player.equipment.weapon);w.buc=-1;assert.equal(g.throwItem(w,[1,0]),false);assert.ok(g.player.inventory.includes(w));});
test('Holy water blesses and unholy water curses without duplicating stacks',()=>{let g=arena(),w=g.player.inventory[0],water=g.createItem('water','potion',{buc:1,count:2});g.addItem(water);w.buc=-1;g.dip(w,water);assert.equal(w.buc,0);g.dip(w,water);assert.equal(w.buc,1);assert.ok(!g.player.inventory.includes(water));});
test('Altars reject stale corpses and only the matching Astral altar grants ascension',()=>{let g=arena(),c=g.createItem('corpse','food',{corpse:'goblin',age:g.turn-100,buc:0});g.addItem(c);Object.assign(g.tile(5,5),{type:'altar',align:'Neutral'});assert.equal(g.offer(c),false);const a=g.createItem('Amulet of Yendor','amulet',{buc:0});g.addItem(a);assert.equal(g.offer(a),false);g.branch='Astral';g.depth=1;g.getLevel();const altar=g.level.tiles.flat().find(t=>t.type==='altar'&&t.align===g.player.align);g.player.x=altar.x;g.player.y=altar.y;assert.ok(g.offer(a));assert.equal(g.won,true);});
test('All four Sokoban floors can be solved by legal pushes and survive revisiting',()=>{const g=new NH.Game('puzzles');g.spawn=()=>null;for(let depth=1;depth<=4;depth++){g.branch='Sokoban';g.depth=depth;g.getLevel();peaceful(g);g.player.x=48;g.player.y=16;assert.equal(g.stairs(1),false);for(const b of [...g.level.boulders]){g.player.x=b.x-1;g.player.y=b.y;for(let n=0;n<11;n++)assert.ok(g.move(1,0));}assert.equal(g.level.puzzle.solved,true);assert.equal(g.level.traps.length,0);assert.equal(g.level.boulders.length,0);}assert.ok(g.level.items.some(o=>['bag of holding','amulet of reflection'].includes(o.item.name)));NH.Game.restore(g.serialize());});
test('Sokoban walls and teleport restrictions prevent magic bypasses',()=>{let g=new NH.Game('soko');g.branch='Sokoban';g.depth=1;g.getLevel();g.player.x=g.level.up.x;g.player.y=g.level.up.y;const pos=[g.player.x,g.player.y];g.teleport();assert.deepEqual([g.player.x,g.player.y],pos);g.ray('digging',[-1,0],'wand');assert.equal(g.tile(28,4).type,'wall');});
test('Mines and Quest endpoints cannot generate phantom levels',()=>{for(const [branch,depth]of [['Mines',8],['Quest',3]]){const g=new NH.Game('limits');g.branch=branch;g.depth=depth;g.getLevel();g.player.x=g.level.down.x;g.player.y=g.level.down.y;assert.equal(g.stairs(1),false);assert.equal(g.depth,depth);}});
test('Ritual requires seven candles, a bell, and the invocation site',()=>{const g=new NH.Game('ritual');g.depth=30;g.getLevel();peaceful(g);g.player.x=g.level.down.x;g.player.y=g.level.down.y;const bell=g.createItem('Bell of Opening','tool',{buc:0}),cand=g.createItem('Candelabrum of Invocation','tool',{buc:0}),book=g.createItem('Book of the Dead','spellbook',{buc:0});for(const i of [bell,cand,book])g.addItem(i);assert.equal(g.read(book),false);g.addItem(g.createItem('wax candle','tool',{count:7,buc:0}));g.apply(cand);g.apply(bell);assert.ok(g.read(book));assert.equal(g.tile(g.player.x,g.player.y).type,'down');g.stairs(1);assert.equal(g.depth,31);const priest=g.level.monsters.find(m=>m.lootSpec?.some(s=>s.name==='Amulet of Yendor'));assert.ok(priest);g.kill(priest);assert.ok(g.level.items.some(o=>o.item.name==='Amulet of Yendor'));});
test('The surface leads through all five planes, not premature victory',()=>{const g=new NH.Game('planes');g.addItem(g.createItem('Amulet of Yendor','amulet',{buc:0}));g.level.monsters=[];g.stairs(-1);assert.equal(g.branch,'Earth');assert.equal(g.won,false);for(const next of ['Air','Fire','Water','Astral']){peaceful(g);g.player.x=g.level.down.x;g.player.y=g.level.down.y;assert.ok(g.stairs(1));assert.equal(g.branch,next);}});
test('Configuration validates types and rejects unknown options',()=>{assert.equal(NH.parseConfig('{}').sortInventory,true);assert.throws(()=>NH.parseConfig('{"quality":"ultra"}'));assert.throws(()=>NH.parseConfig('{"sound":"false"}'));assert.throws(()=>NH.parseConfig('{"cheat":true}'));});
test('Malformed nested inventory and duplicate IDs fail before import',()=>{const g=new NH.Game('bad-save'),mutate=fn=>{let d=JSON.parse(g.serialize());fn(d);assert.throws(()=>NH.Game.restore(JSON.stringify(d)));};mutate(d=>d.player.inventory[0].count=-1);mutate(d=>d.player.inventory[1].id=d.player.inventory[0].id);mutate(d=>d.player.equipment.weapon=9999999);mutate(d=>d.player.status.confusion='forever');mutate(d=>d.player.spells=[{name:'fake spell',knowledge:20}]);mutate(d=>d.levels[g.key].shops=[{id:'bad'}]);});
test('Seeded continuation preserves alerts, bills, containers and future RNG',()=>{const {g,s}=shopGame();g.level.shops[0].debit=35;g.wait();const h=NH.Game.restore(g.serialize());for(let n=0;n<20;n++){g.wait();h.wait();}assert.equal(g.serialize(),h.serialize());});
test('Compact room generation keeps every room connected inside a walled border',()=>{let rooms=0,large=0;for(let seed=0;seed<150;seed++){const l=new NH.Game('rooms-'+seed).level;rooms+=l.rooms.length;large+=l.rooms.filter(r=>r.w>=10||r.h>=7).length;for(let x=0;x<80;x++)assert.equal(l.tiles[0][x].type,'wall'),assert.equal(l.tiles[20][x].type,'wall');for(let y=0;y<21;y++)assert.equal(l.tiles[y][0].type,'wall'),assert.equal(l.tiles[y][79].type,'wall');const q=[l.rooms[0]],seen=new Set([l.rooms[0].cx+','+l.rooms[0].cy]);for(let i=0;i<q.length;i++)for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=q[i].cx+dx,y=q[i].cy+dy,t=l.tiles[y]?.[x],k=x+','+y;if(t&&!seen.has(k)&&!['rock','wall'].includes(t.type)){seen.add(k);q.push({cx:x,cy:y});}}for(const r of l.rooms)assert.ok(seen.has(r.cx+','+r.cy),`room ${r.id} disconnected in seed ${seed}`);}assert.ok(large/rooms<.2,`too many large rooms: ${large}/${rooms}`);});
console.log(`\n${passed} integration checks passed.`);
