// Synthesized ambience, Foley, and feedback. No recordings or audio files.
(() => {
class AudioEngine {
 constructor(){this.enabled=true;this.volume=.30;}
 start(){if(this.ctx){this.ctx.resume();return;}try{this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=this.enabled?this.volume:0;this.master.connect(this.ctx.destination);const size=this.ctx.sampleRate*3,buffer=this.ctx.createBuffer(1,size,this.ctx.sampleRate),data=buffer.getChannelData(0);let brown=0;for(let i=0;i<size;i++){brown=(brown+Math.random()*.025-.0125)/1.015;data[i]=brown;}let src=this.ctx.createBufferSource();src.buffer=buffer;src.loop=true;let filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=230;let gain=this.ctx.createGain();gain.gain.value=.35;src.connect(filter).connect(gain).connect(this.master);src.start();this.tone(55,'sine',100000,.014);this.tone(82.4,'sine',100000,.007);}catch(e){this.enabled=false;}}
 tone(freq,type,duration,volume=.15,slide){if(!this.ctx)return;let t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(10,slide),t+duration);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(this.master);o.start(t);o.stop(t+duration);}
 noise(duration,freq,volume){if(!this.ctx)return;let b=this.ctx.createBuffer(1,this.ctx.sampleRate*duration,this.ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*(1-i/a.length);let s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=freq;g.gain.value=volume;s.connect(f).connect(g).connect(this.master);s.start();}
 play(type){if(!this.ctx||!this.enabled)return;switch(type){case'step':this.noise(.09,600,.13);this.tone(85,'sine',.07,.07,48);break;case'hit':this.noise(.13,1900,.27);this.tone(190,'triangle',.10,.14,65);break;case'hurt':this.noise(.22,500,.27);this.tone(90,'sawtooth',.15,.07,35);break;case'door':case'stone':this.noise(.45,400,.18);this.tone(110,'triangle',.32,.05,53);break;case'pickup':this.tone(1200,'sine',.22,.07);setTimeout(()=>this.tone(1600,'sine',.2,.045),65);break;case'magic':case'beam':this.tone(260,'sine',.5,.14,900);this.tone(390,'triangle',.4,.035,1300);break;case'levelup':case'victory':[261.6,329.6,392,523].forEach((f,i)=>setTimeout(()=>this.tone(f,'sine',.8,.12),i*120));break;case'death':this.tone(110,'sine',2,.2,28);break;case'trap':this.noise(.25,2500,.3);break;case'eat':this.noise(.16,850,.1);break;}}
 toggle(){this.enabled=!this.enabled;if(this.master)this.master.gain.setTargetAtTime(this.enabled?this.volume:0,this.ctx.currentTime,.2);return this.enabled;}
}
globalThis.NH.AudioEngine=AudioEngine;
})();
