/* Front door, preferences, character creation and inventory workflows. */
(() => {
'use strict';
const N=globalThis.NH,$=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
N.installMenus=function(UI){const P=UI.prototype,oldClose=P.close,oldRefresh=P.refresh,oldRows=P.inventoryRows,oldRestore=P.restore;
 P.loadPreferences=function(){try{this.config=N.parseConfig(localStorage.getItem('nethack3d-config')||'{}');}catch{this.config={...N.defaults};}this.applyPreferences();};
 P.applyPreferences=function(){const c=this.config||N.defaults;this.numberPad=c.numberPad;this.game.autoOpenDoors=c.autoOpenDoors;this.game.autopickup=c.autopickup;document.body.classList.toggle('minimal-ui',!!c.minimalUI);if(this.audio.enabled!==c.sound)this.audio.toggle();this.renderer.setQuality(c.quality);};
 P.savePreferences=function(){try{localStorage.setItem('nethack3d-config',JSON.stringify(this.config));}catch{this.toast('Browser storage is unavailable. Export your configuration to keep it.');}this.applyPreferences();};
 P.download=function(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 P.mainMenu=function(){this.cancel();document.body.classList.add('at-menu');const has=key=>{try{return !!localStorage.getItem(key);}catch{return false;}};
  this.show('The Mazes of Menace','NETHACK · THREE DIMENSIONS',`<div class="welcome-panel"><div class="welcome-sigil">◇</div><p class="welcome-lead">Every door, a possibility.<br>Every descent, a story.</p><p class="modal-copy">Choose a calling, gather your courage, and seek the Amulet of Yendor. The dungeon waits for your next move.</p></div><div class="menu-grid"><button id="menu-new" class="menu-card"><span>01</span><strong>New journey</strong><small>Create your adventurer</small></button><button id="menu-import" class="menu-card"><span>02</span><strong>Import journey</strong><small>Open an exported save file</small></button><button id="menu-config" class="menu-card"><span>03</span><strong>Configuration</strong><small>Controls, warnings, sound & display</small></button><button id="menu-help" class="menu-card"><span>04</span><strong>Adventurer’s guide</strong><small>Learn the commands</small></button></div><input id="menu-save-file" type="file" accept=".json,application/json" hidden><p id="menu-error" class="form-error" role="alert"></p>`,[...(this.started&&!this.game.dead&&!this.game.won?[{text:'Resume current journey',action:()=>{this.suspended=false;document.body.classList.remove('at-menu');oldClose.call(this);}}]:[]),...(has('nethack3d-save')?[{text:'Continue saved journey',action:()=>this.restore()}]:[]),...(has('nethack3d-recovery')?[{text:'Recover last session',action:()=>this.restore(true)}]:[])]);
  $('modal-close').hidden=!this.started;if(!this.started&&!$('modal-foot').querySelector('button'))$('modal-foot').innerHTML='<span>Turn-based exploration · 13 callings · 5 races</span>';$('menu-new').onclick=()=>this.newGameMenu();$('menu-import').onclick=()=>$('menu-save-file').click();$('menu-config').onclick=()=>this.options();$('menu-help').onclick=()=>this.help();$('menu-save-file').onchange=e=>this.importJourney(e.target.files[0]);
 };
 P.importJourney=async function(file){if(!file)return;if(file.size>24000000){this.toast('The save file is too large.');return;}try{const game=N.Game.restore(await file.text());this.activateGame(game);this.toast('Journey imported successfully.');}catch(error){const el=$('menu-error');if(el)el.textContent='Cannot import this journey: '+error.message;else this.toast('Cannot import: '+error.message);}};
 P.activateGame=function(game){this.cancel();this.game=game;this.started=true;this.suspended=false;this.ended=false;document.body.classList.remove('at-menu');this.applyPreferences();oldClose.call(this);this.renderer.game=game;this.renderer.buildLevel();this.renderer.focus.set(game.player.x,0,game.player.y);this.refresh();};
 P.restore=function(recovery=false){try{const text=localStorage.getItem(recovery?'nethack3d-recovery':'nethack3d-save');if(!text){this.toast('No saved journey was found.');return;}const game=N.Game.restore(text);this.activateGame(game);game.log('Your journey continues.','story');this.refresh();}catch(e){this.toast('Cannot restore this save: '+e.message);}};
 P.close=function(){if(this.started===false){this.mainMenu();return;}document.body.classList.remove('at-menu');oldClose.call(this);};
 P.newGameMenu=function(){let selected='Knight';const options=(list,value)=>list.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('');
  this.show('Who will enter the dungeon?','CREATE YOUR ADVENTURER',`<div class="form-grid"><div class="form-row"><label for="new-name">NAME</label><input id="new-name" value="Arthur" maxlength="24" autocomplete="off"></div><div class="form-row"><label for="new-seed">DUNGEON SEED</label><input id="new-seed" value="${Math.random().toString(36).slice(2,10).toUpperCase()}" maxlength="40"></div></div><div class="eyebrow form-section-label">YOUR CALLING</div><div class="role-grid">${Object.keys(N.roles).map(r=>`<button class="role-choice ${r===selected?'selected':''}" data-role="${r}">${r}</button>`).join('')}</div><div id="role-description" class="role-description"></div><div class="form-grid identity-grid"><div class="form-row"><label for="new-race">RACE</label><select id="new-race"></select></div><div class="form-row"><label for="new-align">ALIGNMENT</label><select id="new-align"></select></div></div><p class="modal-copy identity-note">Race and alignment follow the calling’s available combinations.</p><p id="create-error" role="alert" class="form-error"></p>`,[{text:'Begin the descent →',action:()=>{try{const game=new N.Game($('new-seed').value||'YENDOR',selected,$('new-name').value||'Arthur',{race:$('new-race').value,align:$('new-align').value});this.activateGame(game);}catch(e){$('create-error').textContent=e.message;}}},{text:'Back to main menu',action:()=>this.mainMenu()}]);
  const updateAlignment=()=>{$('new-align').innerHTML=options(N.characterAlignments(selected,$('new-race').value),N.roles[selected].align);};
  const update=()=>{const r=N.roles[selected],race=$('new-race').value;$('new-race').innerHTML=options(N.roleChoices[selected],race);updateAlignment();$('role-description').innerHTML=`<strong>${selected}</strong><span class="role-vitals">${r.hp} HP · ${selected==='Healer'?15:r.pw} POWER</span><br>${r.gear.slice(0,4).map(i=>esc(i[0])).join(' · ')}${r.spells?.length?'<br>Magic: '+esc(r.spells.join(', ')):''}`;};
  $('modal-body').querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{selected=b.dataset.role;$('modal-body').querySelectorAll('[data-role]').forEach(b=>b.classList.toggle('selected',b.dataset.role===selected));update();});$('new-race').onchange=updateAlignment;update();
 };
 P.options=function(){const c=this.config||N.defaults,labels={minimalUI:['Minimal UI','Hide the top bar and extra HUD controls; keep map, nearby creatures, chronicle, and core stats.'],autoOpenDoors:['Auto-open doors','Walk through unlocked doors.'],autopickup:['Pick up gold automatically','Use comma to collect other objects.'],sortInventory:['Sort inventory','Group by category, then by name. Item letters stay the same.'],pauseOnHunger:['Pause when hungry','Stop movement and acknowledge changes in hunger.'],pauseOnBurden:['Pause when burdened','Review changes in carrying load.'],pauseOnLowHP:['Pause at critical health','Interrupt at one quarter of maximum health.'],sound:['Sound','Procedural dungeon ambience and effects.']};
  this.show('Make yourself at home','CONFIGURATION',`<div class="option-row"><label for="opt-numberPad">Movement layout</label><select id="opt-numberPad"><option value="true" ${c.numberPad?'selected':''}>Number pad</option><option value="false" ${!c.numberPad?'selected':''}>Classic vi</option></select></div>${Object.entries(labels).map(([k,[label,help]])=>`<div class="option-row"><label for="opt-${k}">${label}<small>${help}</small></label><input type="checkbox" id="opt-${k}" ${c[k]?'checked':''}></div>`).join('')}<div class="option-row"><label for="opt-quality">Render quality</label><select id="opt-quality"><option value="high" ${c.quality==='high'?'selected':''}>High · shadows</option><option value="low" ${c.quality==='low'?'selected':''}>Economy</option></select></div><details class="config-editor"><summary>Edit configuration file</summary><p class="modal-copy">Changes are stored in this browser. Export a JSON file to keep or transfer your preferences.</p><textarea id="config-text" spellcheck="false" aria-label="Configuration JSON">${esc(JSON.stringify(c,null,2))}</textarea><div class="item-actions"><button id="config-apply">Apply JSON</button><button id="config-export">Export file</button><button id="config-import">Import file</button><input type="file" id="config-file" accept=".json,application/json" hidden></div><p id="config-error" class="form-error" role="alert"></p></details>`,[{text:'Done',action:()=>this.started?this.close():this.mainMenu()},{text:'Reset defaults',action:()=>{this.config={...N.defaults};this.savePreferences();this.options();}}]);
  for(const k of Object.keys(N.defaults))$('opt-'+k).onchange=e=>{this.config[k]=k==='quality'?e.target.value:k==='numberPad'?e.target.value==='true':e.target.checked;this.savePreferences();$('config-text').value=JSON.stringify(this.config,null,2);};
  const apply=text=>{try{this.config=N.parseConfig(text);this.savePreferences();this.options();this.toast('Configuration saved.');}catch(e){$('config-error').textContent=e.message;}};$('config-apply').onclick=()=>apply($('config-text').value);$('config-export').onclick=()=>this.download(JSON.stringify(this.config,null,2),'nethack3d-config.json');$('config-import').onclick=()=>$('config-file').click();$('config-file').onchange=async e=>{const f=e.target.files[0];if(f&&f.size<100000)apply(await f.text());else $('config-error').textContent='Choose a configuration file smaller than 100 KB.';};
 };
 P.inventoryRows=function(list){return oldRows.call(this,this.config?.sortInventory!==false?this.game.sortedInventory(list):list);};
 P.refresh=function(){oldRefresh.call(this);const g=this.game,c=this.config||N.defaults,name=N.themes[g.level.theme]?.name||g.branch;$('location').textContent=name;$('depth').textContent=`LEVEL ${String(g.depth).padStart(2,'0')} · ${N.branches[g.branch]?.name||g.branch}`;
  $('quest-step').textContent=g.won?'You have ascended':g.branch==='Astral'?'Offer the Amulet at your aligned high altar':g.allInventory().some(i=>i.name==='Amulet of Yendor')?'Return to the surface and enter the Planes':g.level.puzzle?`Fill ${g.level.puzzle.remaining} remaining pits`:g.branch==='Quest'?'Find the Bell of Opening':'Seek the Bell, Candelabrum, and Book';
  const alerts=(g.alerts||[]).splice(0);for(const a of alerts){g.log(a.title+'.','warning');if((a.kind==='hunger'&&c.pauseOnHunger||a.kind==='burden'&&c.pauseOnBurden||a.kind==='lowHP'&&c.pauseOnLowHP)&&!g.dead&&!g.won&&this.started!==false){this.cancel();this.show(a.title,'JOURNEY PAUSED',`<p class="modal-copy">${esc(a.text)}</p><p class="modal-copy">Time is stopped. Review your supplies before continuing.</p>`,[{text:'Continue carefully',action:()=>this.close()},{text:'Open inventory',action:()=>this.inventory()}]);break;}}
 };
 P.useTool=function(i){if(i.contents)return this.containerMenu(i);if(['skeleton key','lock pick','credit card','pick-axe','mirror','stethoscope','leash','saddle','grappling hook','fire horn','frost horn'].includes(i.name))this.askDirection('Apply '+i.name+' in which direction?',d=>this.game.apply(i,d));else this.game.apply(i);};
 P.containerMenu=function(container){container.contents||=[];const list=container.contents;this.show(this.game.label(container),'CONTAINER',this.inventoryRows(list),[{text:'Put an item inside',action:()=>this.selectItem('Store an item',i=>i!==container&&!Object.values(this.game.player.equipment).includes(i.id),i=>{this.game.storeItem(container,i);this.containerMenu(container);})},{text:'Close container',action:()=>this.close()}]);this.wireItems(list,i=>{this.game.takeItem(container,i);this.refresh();if(!this.game.dead)this.containerMenu(container);});};
};
})();
