/* All geometry, surface maps, particles, and animation are synthesized here. */
(() => {
'use strict';
const N=globalThis.NH,T=globalThis.THREE;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const palette={CLR_BLACK:0x42444a,CLR_RED:0x973d32,CLR_GREEN:0x708157,CLR_BROWN:0x8c7153,CLR_BLUE:0x547488,CLR_MAGENTA:0x8c5481,CLR_CYAN:0x549e98,CLR_GRAY:0xa1a1a0,CLR_ORANGE:0xbe723d,CLR_BRIGHT_GREEN:0x819a4b,CLR_YELLOW:0xc6a25c,CLR_BRIGHT_BLUE:0x6c9dc1,CLR_BRIGHT_MAGENTA:0xb578a3,CLR_BRIGHT_CYAN:0x86c2b8,CLR_WHITE:0xc8c6b7,HI_DOMESTIC:0xb4a082,HI_LORD:0x9570a1,HI_METAL:0x9ca6a8};
function canvasTexture(kind,seed=1){const rng=new N.RNG(seed),c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d');ctx.fillStyle=kind==='wood'?'#493629':'#717474';ctx.fillRect(0,0,256,256);
 const pixels=ctx.getImageData(0,0,256,256);for(let y=0;y<256;y++)for(let x=0;x<256;x++){let i=(y*256+x)*4,v=(rng.next()-.5)*28+Math.sin(x*.07+Math.sin(y*.03)*3)*5+Math.sin(y*.09)*5;if(kind==='wood')v+=Math.sin(x*.6+Math.sin(y*.01)*2)*12;for(let k=0;k<3;k++)pixels.data[i+k]=clamp(pixels.data[i+k]+v,0,255);}ctx.putImageData(pixels,0,0);
 if(kind!=='wood'){for(let i=0;i<90;i++){ctx.strokeStyle=`rgba(${rng.next()<.5?'15,22,24':'192,197,184'},${rng.next()*.13})`;ctx.lineWidth=rng.next()*2;ctx.beginPath();let x=rng.next()*256,y=rng.next()*256;ctx.moveTo(x,y);ctx.lineTo(x+rng.next()*35,y+rng.next()*12);ctx.stroke();}for(let i=0;i<4;i++){ctx.strokeStyle='rgba(10,19,20,.20)';ctx.lineWidth=.7;ctx.beginPath();let x=rng.next()*256,y=rng.next()*256;ctx.moveTo(x,y);for(let n=0;n<4;n++){x+=rng.next()*18-6;y+=rng.next()*15;ctx.lineTo(x,y);}ctx.stroke();}}
 const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.anisotropy=4;return tex;}
function radialTexture(){const c=document.createElement('canvas');c.width=c.height=64;const g=c.getContext('2d'),r=g.createRadialGradient(32,32,0,32,32,32);r.addColorStop(0,'rgba(255,247,199,1)');r.addColorStop(.15,'rgba(255,203,104,.8)');r.addColorStop(.4,'rgba(249,116,29,.15)');r.addColorStop(1,'rgba(255,70,0,0)');g.fillStyle=r;g.fillRect(0,0,64,64);return new T.CanvasTexture(c);}
function bevelBox(w,h,d,bevel=.035){let s=new T.Shape(),x=-w/2,z=-d/2;s.moveTo(x,z);s.lineTo(x+w,z);s.lineTo(x+w,z+d);s.lineTo(x,z+d);s.closePath();let g=new T.ExtrudeGeometry(s,{depth:Math.max(.01,h-2*bevel),bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:bevel,bevelThickness:bevel});g.rotateX(-Math.PI/2);g.translate(0,-h/2+bevel,0);return g;}
class Renderer {
 constructor(canvas,game){this.canvas=canvas;this.game=game;this.scene=new T.Scene();this.scene.background=new T.Color(0x0b1114);this.scene.fog=new T.FogExp2(0x0b1114,.024);this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.23;
  this.camera=new T.PerspectiveCamera(37,1,.1,120);this.focus=new T.Vector3(game.player.x,0,game.player.y);this.zoom=19;this.targetZoom=19;this.angle=0;this.targetAngle=0;this.shake=0;this.models=new Map();this.effects=[];this.torches=[];this.water=[];this.batches=[];this.tileObjects=[];this.lastTurn=-1;this.lastStructureCheckTurn=-1;this.itemSceneKey='';this.itemEntries=[];this.itemModels=new Map();this.trapModels=new Map();this.occupancyKey='';this.reusableLook=new T.Vector3();this.reusableOffset=new T.Vector3();this.raycaster=new T.Raycaster();this.pointer=new T.Vector2();this.clock=new T.Clock();this.quality='high';
  this.geo={box:new T.BoxGeometry(1,1,1),sphere:new T.SphereGeometry(1,12,8),ico:new T.IcosahedronGeometry(1,1),cyl:new T.CylinderGeometry(1,1,1,12),cone:new T.ConeGeometry(1,1,8),torus:new T.TorusGeometry(1,.1,6,28)};this.sharedGeometry=new Set(Object.values(this.geo));
  const stone=canvasTexture('stone',32),wood=canvasTexture('wood',83);this.mats={floor:new T.MeshStandardMaterial({color:0x838b86,map:stone,bumpMap:stone,bumpScale:.095,roughness:.84}),stone:new T.MeshStandardMaterial({color:0xa2a197,map:stone,bumpMap:stone,bumpScale:.16,roughness:.9}),dark:new T.MeshStandardMaterial({color:0x242e31,map:stone,roughness:.96}),metal:new T.MeshStandardMaterial({color:0x8e9ba2,metalness:.78,roughness:.32}),gold:new T.MeshStandardMaterial({color:0xbc9150,metalness:.76,roughness:.36}),wood:new T.MeshStandardMaterial({color:0x90725b,map:wood,bumpMap:wood,bumpScale:.08,roughness:.8}),leather:new T.MeshStandardMaterial({color:0x48362a,roughness:.92}),cloth:new T.MeshStandardMaterial({color:0x7b3437,roughness:1,side:T.DoubleSide}),skin:new T.MeshStandardMaterial({color:0xc5a388,roughness:.87}),bone:new T.MeshStandardMaterial({color:0xc2baa0,roughness:.8}),black:new T.MeshStandardMaterial({color:0x141b1d,roughness:.7}),water:new T.MeshStandardMaterial({color:0x206b72,metalness:.65,roughness:.18,transparent:true,opacity:.85}),rune:new T.MeshStandardMaterial({color:0x87c1b7,emissive:0x388f8a,emissiveIntensity:.8,roughness:.5})};this.glow=radialTexture();
  this.scene.add(new T.HemisphereLight(0xa3c3d2,0x24211d,1.1));this.sun=new T.DirectionalLight(0xb6d4e1,2.0);this.sun.position.set(-8,18,-6);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);Object.assign(this.sun.shadow.camera,{left:-20,right:20,top:20,bottom:-20,near:.5,far:60});this.sun.shadow.bias=-.0007;this.sun.shadow.normalBias=.03;this.scene.add(this.sun,this.sun.target);
  this.playerLight=new T.PointLight(0xffcc8e,13,10,2);this.scene.add(this.playerLight);this.lights=Array.from({length:6},()=>{let l=new T.PointLight(0xffa64d,28,11,2);this.scene.add(l);return l;});
  const base=new T.Mesh(new T.PlaneGeometry(240,160),new T.MeshStandardMaterial({color:0x0e1518,roughness:1}));base.rotation.x=-Math.PI/2;base.position.set(40,-.42,10);base.receiveShadow=true;this.scene.add(base);
  this.cursor=new T.Mesh(new T.RingGeometry(.40,.43,4),new T.MeshBasicMaterial({color:0xe8c17a,transparent:true,opacity:.7,side:T.DoubleSide,depthWrite:false}));this.cursor.rotation.set(-Math.PI/2,0,Math.PI/4);this.cursor.position.y=.025;this.cursor.visible=false;this.scene.add(this.cursor);
  this.heroRing=new T.Mesh(new T.RingGeometry(.38,.405,48),new T.MeshBasicMaterial({color:0xd3b06d,transparent:true,opacity:.65,side:T.DoubleSide,depthWrite:false}));this.heroRing.rotation.x=-Math.PI/2;this.scene.add(this.heroRing);
  this.buildLevel();this.resize();this.animate=this.animate.bind(this);this.raf=requestAnimationFrame(this.animate);window.addEventListener('resize',()=>this.resize());canvas.addEventListener('wheel',e=>{e.preventDefault();this.targetZoom=clamp(this.targetZoom+e.deltaY*.015,11,32);},{passive:false});canvas.addEventListener('pointermove',e=>this.hover(e));canvas.addEventListener('pointerleave',()=>this.cursor.visible=false);
 }
 material(color){return new T.MeshStandardMaterial({color,roughness:.78});}
 mesh(g,mat,parent,pos=[0,0,0],scale=[1,1,1],rot){let m=new T.Mesh(typeof g==='string'?this.geo[g]:g,typeof mat==='string'?this.mats[mat]:mat);m.position.set(...pos);m.scale.set(...scale);if(rot)m.rotation.set(...rot);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 rod(a,b,r,mat,parent){let av=new T.Vector3(...a),bv=new T.Vector3(...b),delta=bv.clone().sub(av),m=this.mesh('cyl',mat,parent,av.clone().add(bv).multiplyScalar(.5).toArray(),[r,delta.length(),r]);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),delta.normalize());return m;}
 batch(geometry,material,entries){if(!entries.length)return;let mesh=new T.InstancedMesh(geometry,material,entries.length);mesh.castShadow=true;mesh.receiveShadow=true;mesh.frustumCulled=false;this.world.add(mesh);this.batches.push({mesh,entries});}
 buildLevel(){
  if(this.world){this.scene.remove(this.world);this.world.traverse(o=>{if(o.isInstancedMesh)o.dispose();if(o.geometry&&!Object.values(this.geo).includes(o.geometry)&&!o.userData.shared)o.geometry.dispose();});}this.world=new T.Group();this.scene.add(this.world);this.batches=[];this.tileObjects=[];this.torches=[];this.water=[];for(let m of this.models.values())this.scene.remove(m.group);this.models.clear();const theme=N.themes[this.game.level.theme]||N.themes.Dungeons;for(const key of ['stone','floor','cloth'])this.mats[key].color.setHex(theme[key]);this.scene.background.setHex(theme.fog);this.scene.fog.color.setHex(theme.fog);this.sun.color.setHex(theme.light);const l=this.game.level,rng=new N.RNG(this.game.seed+this.game.key+'art'),floor=[],brick=[],cap=[],base=[],rubble=[];
  for(let row of l.tiles)for(let t of row){if(t.type==='rock')continue;let {x,y}=t,color=new T.Color(0xa5ada7).multiplyScalar(.78+rng.next()*.3);
   if(['wall','secret'].includes(t.type)){base.push({t,pos:[x,.42,y],scale:[.70,.84,.70],color:0x5a6260});let alongX=l.tiles[y-1]?.[x]?.type==='floor'||l.tiles[y+1]?.[x]?.type==='floor';for(let h=0;h<3;h++)for(let k=0;k<2;k++){let off=(k-.5)*.49+(h%2? .03:0);brick.push({t,pos:[x+(alongX?off:0),.18+h*.30,y+(alongX?0:off)],scale:alongX?[.46,.26,.73]:[.73,.26,.46],color:color.clone().multiplyScalar(.8+rng.next()*.15)});}cap.push({t,pos:[x,1.02,y],scale:[.96,.12,.96],color:color.clone().multiplyScalar(1.08)});
   }else {if(rng.next()<.23){let horizontal=rng.next()<.5;for(let s of [-1,1])floor.push({t,pos:[x+(horizontal?s*.246:0),-.083+rng.next()*.01,y+(horizontal?0:s*.246)],scale:horizontal?[.463,.16,.958]:[.958,.16,.463],rot:0,color:color.clone().multiplyScalar(.96+rng.next()*.08)});}else floor.push({t,pos:[x,-.08+rng.next()*.012,y],scale:[.958,.16,.958],rot:rng.int(0,3)*Math.PI/2,color});if(rng.next()<.22){for(let j=0;j<rng.int(1,3);j++)rubble.push({t,pos:[x+(rng.next()-.5)*.8,.035,y+(rng.next()-.5)*.8],scale:[rng.next()*.1+.035,.03,rng.next()*.09+.03],rot:rng.next()*6.28,color:0x73786f});}
    if(!['floor','corridor'].includes(t.type))this.addFeature(t,rng);
   }
  }
  this.batch(bevelBox(1,1,1,.018),this.mats.floor,floor);this.batch(this.geo.box,this.mats.dark,base);this.batch(bevelBox(1,1,1,.035),this.mats.stone,brick);this.batch(bevelBox(1,1,1,.035),this.mats.stone,cap);this.batch(this.geo.ico,this.mats.stone,rubble);
  for(let r of l.rooms){const canDecorate=r.w>=5&&r.h>=5;if(canDecorate)for(let [x,y]of [[r.x,r.y],[r.x+r.w-1,r.y],[r.x,r.y+r.h-1],[r.x+r.w-1,r.y+r.h-1]]){let t=l.tiles[y][x],g=new T.Group();g.position.set(x,0,y);this.mesh('box','dark',g,[0,.1,0],[.54,.2,.54]);this.mesh('cyl','stone',g,[0,.73,0],[.19,1.14,.19]);for(let h of [.22,1.3])this.mesh('box','stone',g,[0,h,0],[.46,.16,.46]);this.mesh('box','gold',g,[0,1.22,0],[.32,.06,.32]);this.world.add(g);this.tileObjects.push({group:g,t});}
   if(canDecorate)for(let [x,y]of [[r.x+1,r.y+1],[r.x+r.w-2,r.y+r.h-2]])this.brazier(x,y,l.tiles[y][x],rng);
   if(r.id===0){const g=new T.Group();g.position.set(r.x+r.w/2-.5,.007,r.y+r.h/2-.5);for(let radius of [1.43,1.52,1.7]){const m=new T.Mesh(new T.RingGeometry(radius,radius+.018,64),new T.MeshStandardMaterial({color:0x777663,roughness:.95,transparent:true,opacity:.38,side:T.DoubleSide}));m.rotation.x=-Math.PI/2;g.add(m);}for(let a=0;a<8;a++){let angle=a*Math.PI/4;this.mesh('box','dark',g,[Math.sin(angle)*1.62,0,Math.cos(angle)*1.62],[.065,.01,.12],[0,angle,0]);}this.world.add(g);this.tileObjects.push({group:g,t:l.tiles[Math.floor(g.position.z)][Math.floor(g.position.x)]});
    for(let x of [r.x+3,r.x+r.w-4]){let t=l.tiles[r.y][x],banner=new T.Group();banner.position.set(x,0,r.y-.42);this.mesh('box','dark',banner,[0,1.24,-.14],[.20,2.48,.26]);this.mesh('box','stone',banner,[0,2.38,-.10],[.45,.16,.39]);this.rod([-.42,2.20,0],[.42,2.20,0],.024,'gold',banner);let shape=new T.Shape();shape.moveTo(-.32,2.18);shape.lineTo(.32,2.18);shape.lineTo(.32,1.08);shape.lineTo(0,.88);shape.lineTo(-.32,1.08);shape.closePath();this.mesh(new T.ShapeGeometry(shape),this.mats.cloth,banner,[0,0,.035]);this.mesh('box','gold',banner,[0,1.64,.045],[.021,.60,.009]);this.mesh('box','gold',banner,[0,1.72,.045],[.26,.022,.009]);let ring=this.mesh('torus','gold',banner,[0,1.58,.05],[.13,.13,.13]);this.world.add(banner);this.tileObjects.push({group:banner,t});}
   }
  }
  for(let b of l.boulders){let g=new T.Group();g.position.set(b.x,0,b.y);this.mesh('ico','stone',g,[0,.42,0],[.46,.48,.44],[.3,rng.next()*6,.2]);this.world.add(g);this.tileObjects.push({group:g,b,t:l.tiles[b.y][b.x]});}
  // Sparse floating dust, generated once per level.
  const positions=new Float32Array(240*3);for(let i=0;i<240;i++){positions[i*3]=rng.next()*80;positions[i*3+1]=rng.next()*2.6+.1;positions[i*3+2]=rng.next()*21;}const dustG=new T.BufferGeometry();dustG.setAttribute('position',new T.BufferAttribute(positions,3));this.dust=new T.Points(dustG,new T.PointsMaterial({color:0xe7c798,size:.025,transparent:true,opacity:.45,depthWrite:false}));this.world.add(this.dust);
  this.levelKey=this.game.key;this.structure=this.structureKey();this.lastStructureCheckTurn=this.game.turn;this.itemSceneKey='';this.itemGroup=null;this.itemModels.clear();this.trapModels.clear();this.sync(true);
 }
 structureKey(){return this.game.level.tiles.flat().map(t=>t.x+','+t.y+':'+(['door','openDoor'].includes(t.type)?'door':t.type)+':'+(t.align||'')).join('|')+this.game.level.boulders.map(b=>b.id+':'+b.x+','+b.y).join('|');}
 addFeature(t,rng){const g=new T.Group();g.position.set(t.x,0,t.y);this.world.add(g);this.tileObjects.push({group:g,t,doorFeature:['door','openDoor'].includes(t.type)});
  if(['door','openDoor'].includes(t.type)){this.mesh(bevelBox(.86,1.3,.14,.025),'wood',g,[0,.66,0]);for(let x of [-.32,-.16,0,.16,.32])this.mesh('box','dark',g,[x,.67,-.08],[.018,1.22,.012]);for(let y of [.26,1.08])this.mesh('box','metal',g,[0,y,.09],[.9,.065,.04]);this.mesh('torus','gold',g,[.24,.63,.13],[.045,.045,.045]);let lr=this.game.tile(t.x-1,t.y)?.type,rr=this.game.tile(t.x+1,t.y)?.type;if(t.axis==='x'||!t.axis&&(['floor','corridor'].includes(lr)||['floor','corridor'].includes(rr)))g.rotation.y=Math.PI/2;}
  else if(['up','down','branch'].includes(t.type)){this.mesh('box','black',g,[0,-.005,0],[.94,.04,.96]);for(let s=0;s<6;s++)this.mesh('box','stone',g,[0,.025+s*.055,(s-2.5)*.14],[.81,.07,.13]);for(let x of [-.46,.46]){this.mesh('box','stone',g,[x,.2,0],[.1,.4,1.05]);this.mesh('box','gold',g,[x,.415,0],[.08,.025,1]);}if(t.type==='up'){this.mesh('box','stone',g,[0,1.2,-.49],[1.02,.23,.23]);for(let x of [-.45,.45])this.mesh('box','stone',g,[x,.7,-.49],[.18,1.2,.22]);}let c=t.type==='up'?0xbc9c65:0x4e8c98;const glow=new T.PointLight(c,3,3,2);glow.position.set(0,.35,0);g.add(glow);}
  else if(t.type==='fountain'){this.mesh('cyl','dark',g,[0,.1,0],[.58,.2,.58]);this.mesh('cyl','stone',g,[0,.25,0],[.5,.18,.5]);this.mesh('torus','stone',g,[0,.36,0],[.46,.46,.46],[Math.PI/2,0,0]);this.mesh('cyl','water',g,[0,.34,0],[.40,.025,.40]);this.mesh('cyl','stone',g,[0,.55,0],[.12,.7,.12]);this.mesh('sphere','gold',g,[0,.96,0],[.095,.095,.095]);for(let k=0;k<4;k++){let a=k*Math.PI/2;let curve=new T.QuadraticBezierCurve3(new T.Vector3(0,.87,0),new T.Vector3(Math.sin(a)*.42,1.08,Math.cos(a)*.42),new T.Vector3(Math.sin(a)*.32,.36,Math.cos(a)*.32));this.mesh(new T.TubeGeometry(curve,16,.011,5,false),'water',g);}this.water.push(g);const light=new T.PointLight(0x6cacb6,4,3.5,2);light.position.y=.8;g.add(light);}
  else if(t.type==='altar'){const altarCloth=this.material(({Lawful:0xe2d9b8,Neutral:0x8d9990,Chaotic:0x813945,Unaligned:0x29252e})[t.align]||0x8d9990);this.mesh('box','dark',g,[0,.12,0],[.9,.24,.8]);this.mesh('box','stone',g,[0,.45,0],[.66,.6,.5]);this.mesh(bevelBox(1,.15,.8,.04),'stone',g,[0,.78,0]);this.mesh('box',altarCloth,g,[0,.87,.07],[.36,.016,.69]);for(let x of [-.34,.34]){this.mesh('cyl','gold',g,[x,.94,-.18],[.06,.16,.06]);this.flame(g,x,1.07,-.18,.20);}this.mesh('torus','gold',g,[0,.5,.265],[.14,.14,.14]);}
  else if(t.type==='grave'){this.mesh(bevelBox(.48,.65,.16,.045),'stone',g,[0,.37,-.2],[1,1,1],[0,-.12,0]);this.mesh('box','dark',g,[0,.49,-.106],[.22,.035,.008]);this.mesh('box','dark',g,[0,.45,-.105],[.035,.24,.008]);this.mesh('box','dark',g,[0,.014,.15],[.45,.022,.67]);}
  else if(t.type==='sink'){this.mesh('box','stone',g,[0,.3,0],[.65,.6,.55]);this.mesh('box','water',g,[0,.61,0],[.48,.02,.37]);this.rod([0,.65,-.22],[0,.95,-.22],.025,'metal',g);this.rod([0,.95,-.22],[0,.95,0],.025,'metal',g);}
  else if(t.type==='throne'){this.mesh('box','gold',g,[0,.45,0],[.66,.15,.62]);this.mesh('box','gold',g,[0,.95,-.28],[.65,1.05,.12]);this.mesh('box','cloth',g,[0,.95,-.20],[.48,.75,.06]);for(let x of [-.3,.3])for(let z of [-.25,.25])this.mesh('cyl','gold',g,[x,.35,z],[.045,.65,.045]);}
  else if(t.type==='portal'){this.mesh('torus','rune',g,[0,.66,0],[.55,.55,.55]);this.mesh('cyl','dark',g,[0,.05,0],[.65,.1,.65]);}
  else if(t.type==='water'||t.type==='lava'){this.mesh('box','water',g,[0,.01,0],[.98,.03,.98]);this.water.push(g);}
 }
 flame(g,x,y,z,scale=.4){let geometry=new T.LatheGeometry([[0,-.45],[.14,-.3],[.19,-.08],[.12,.19],[.05,.37],[0,.68]].map(p=>new T.Vector2(...p)),12);let mesh=this.mesh(geometry,new T.MeshBasicMaterial({color:0xffb146}),g,[x,y,z],[scale,scale,scale]);let inner=this.mesh('sphere',new T.MeshBasicMaterial({color:0xffedb0}),g,[x,y-scale*.12,z+.01],[scale*.10,scale*.30,scale*.10]);let s=new T.Sprite(new T.SpriteMaterial({map:this.glow,color:0xffaa52,blending:T.AdditiveBlending,depthWrite:false,opacity:.8}));s.position.set(x,y,z);s.scale.set(scale*2.5,scale*3.5,1);g.add(s);return{mesh,inner,halo:s,phase:Math.random()*6,base:y,scale};}
 brazier(x,y,t,rng){let g=new T.Group();g.position.set(x,0,y);for(let a=0;a<3;a++){let angle=a*2.094;this.rod([Math.sin(angle)*.22,.03,Math.cos(angle)*.22],[0,.65,0],.035,'metal',g);}this.mesh('cyl','metal',g,[0,.57,0],[.24,.12,.24]);this.mesh('torus','gold',g,[0,.63,0],[.24,.24,.24],[Math.PI/2,0,0]);const flame=this.flame(g,0,.86,0,.53);this.world.add(g);this.tileObjects.push({group:g,t});this.torches.push({group:g,t,...flame});}
 humanoid(kind,color,hero=false){const g=new T.Group(),body=new T.Group();g.add(body);const d=N.monsterDef(kind),skeletal=d?.family==='ZOMBIE'||d?.family==='MUMMY'||kind.includes('skeleton'),skin=hero?this.mats.skin:this.material(skeletal?0xb7b2a0:color),armor=hero?this.mats.metal:this.material(new T.Color(color).multiplyScalar(.65)),cloth=hero?this.mats.cloth:this.material(new T.Color(color).multiplyScalar(.52));
  const limbs=[];for(let sign of [-1,1]){let leg=new T.Group();leg.position.set(sign*.12,.46,0);body.add(leg);this.mesh('cyl',hero?'leather':cloth,leg,[0,-.12,0],[.074,.28,.075]);this.mesh('box',hero?'metal':armor,leg,[0,-.3,.05],[.14,.16,.23]);limbs.push(leg);}
  this.mesh('sphere',hero?'leather':cloth,body,[0,.51,0],[.19,.17,.13]);this.mesh('sphere',armor,body,[0,.76,0],[.22,.27,.15]);this.mesh('box','leather',body,[0,.59,.012],[.4,.075,.29]);this.mesh('box','gold',body,[0,.59,.17],[.075,.07,.03]);
  this.mesh('cyl',skin,body,[0,1.00,0],[.065,.11,.065]);this.mesh('sphere',skin,body,[0,1.14,.012],[.135,.17,.13]);this.mesh('sphere','black',body,[0,1.17,-.035],[.14,.15,.12]);for(let s of [-1,1])this.mesh('sphere',hero?'black':new T.MeshBasicMaterial({color:0xd1b05e}),body,[s*.052,1.17,.127],[.016,.013,.01]);
  if(hero||/ORC|HUMAN|GNOME/.test(d?.family||'')){this.mesh('sphere',armor,body,[0,1.25,-.006],[.16,.12,.15]);this.mesh('box','gold',body,[0,1.25,.145],[.033,.14,.016]);for(let s of [-1,1])this.mesh('box',armor,body,[s*.132,1.14,.055],[.035,.16,.1],[0,0,s*.12]);}
  if(d?.family==='ORC')for(let s of [-1,1])this.mesh('cone',skin,body,[s*.17,1.17,0],[.06,.15,.055],[0,0,-s*1.15]);
  for(let s of [-1,1]){let arm=new T.Group();arm.position.set(s*.25,.9,0);body.add(arm);this.mesh('sphere',armor,arm,[0,0,0],[.13,.12,.14]);this.mesh('cyl',hero?'leather':cloth,arm,[s*.018,-.16,.025],[.065,.27,.065],[0,0,s*.15]);this.mesh('sphere',skin,arm,[s*.04,-.31,.075],[.062,.065,.06]);limbs.push(arm);if(s===1){const sword=new T.Group();sword.position.set(.04,-.30,.13);arm.add(sword);this.mesh('cyl','leather',sword,[0,.03,0],[.025,.19,.025]);this.mesh('box','gold',sword,[0,.12,0],[.22,.035,.055]);this.mesh('box','metal',sword,[0,.41,0],[.063,.57,.021]);this.mesh('cone','metal',sword,[0,.73,0],[.032,.11,.017]);g.userData.weapon=arm;}else if(hero){let shield=this.mesh(new T.CylinderGeometry(.23,.23,.055,8),'metal',arm,[-.075,-.22,.17],[1,1,1],[Math.PI/2,0,.18]);this.mesh('sphere','gold',arm,[-.075,-.22,.21],[.065,.065,.025]);}}
  // A curved cloth cape with a scalloped hem, animated by deforming its vertices.
  if(hero||d?.family==='HUMAN'){let geometry=new T.PlaneGeometry(.49,.68,8,10);let a=geometry.attributes.position;for(let i=0;i<a.count;i++){let x=a.getX(i),y=a.getY(i),v=(.34-y)/.68;a.setXYZ(i,x*(.7+v*.5),y,-.035-Math.sin(v*Math.PI)*.07); }geometry.computeVertexNormals();let cape=this.mesh(geometry,cloth,body,[0,.66,-.18]);cape.userData.original=Float32Array.from(a.array);g.userData.cape=cape;}
  g.userData.body=body;g.userData.limbs=limbs;return g;
 }
 wizardPlayer(){
  const g=new T.Group(),body=new T.Group(),limbs=[];g.add(body);
  const robe=this.material(0x3e4d68),robeDark=this.material(0x27364f),trim=this.mats.gold,skin=this.mats.skin;
  for(const sign of [-1,1]){const leg=new T.Group();leg.position.set(sign*.12,.42,0);body.add(leg);this.mesh('cyl','leather',leg,[0,-.10,0],[.07,.25,.07]);this.mesh('box',robeDark,leg,[0,-.28,.03],[.15,.12,.22]);limbs.push(leg);}
  this.mesh('cone',robe,body,[0,.60,0],[.31,.70,.31]);this.mesh('cyl',trim,body,[0,.48,.02],[.27,.035,.27]);
  this.mesh('sphere',robeDark,body,[0,.92,0],[.22,.19,.16]);this.mesh('cyl',trim,body,[0,.76,.02],[.23,.028,.23]);
  this.mesh('cyl',skin,body,[0,1.09,0],[.065,.11,.065]);this.mesh('sphere',skin,body,[0,1.23,.01],[.14,.17,.13]);
  // Pointed hood and a shadowed brim create a readable wizard silhouette.
  this.mesh('cone',robeDark,body,[0,1.38,-.01],[.24,.43,.24]);this.mesh('torus',robe,body,[0,1.22,.015],[.23,.23,.23],[Math.PI/2,0,0]);
  for(const sign of [-1,1])this.mesh('sphere','black',body,[sign*.052,1.23,.13],[.018,.014,.01]);
  for(const sign of [-1,1]){const arm=new T.Group();arm.position.set(sign*.24,.90,0);body.add(arm);this.mesh('cyl',robe,arm,[sign*.02,-.12,.01],[.075,.30,.075],[0,0,sign*.16]);this.mesh('sphere',skin,arm,[sign*.05,-.29,.08],[.064,.06,.06]);limbs.push(arm);}
  // A small spellbook and belt make the silhouette read as a class model even
  // when the camera is pulled back.
  this.mesh('box','leather',body,[0,.64,.26],[.22,.18,.06]);this.mesh('box',trim,body,[0,.64,.295],[.15,.02,.012]);
  this.mesh('cone',robeDark,body,[0,.63,-.16],[.28,.62,.10]);g.userData.body=body;g.userData.limbs=limbs;return g;
 }
 creature(kind){let d=N.monsterDef(kind)||{},color=d.family==='ORC'?0x7e8f68:palette[d.color]||0x81775d,f=d.family,g=new T.Group(),mat=this.material(color),dark=this.material(new T.Color(color).multiplyScalar(.62));
  if(['DOG','FELINE','RODENT','UNICORN','QUADRUPED','LIZARD','SPIDER'].includes(f)){const isRat=f==='RODENT',isSpider=f==='SPIDER';this.mesh('sphere',mat,g,[0,.29,0],[.19,.22,.34]);this.mesh('sphere',mat,g,[0,.43,.32],[.17,.16,.18]);this.mesh('sphere',dark,g,[0,.39,.47],[.1,.07,.1]);for(let s of [-1,1]){if(!isSpider)this.mesh('cone',mat,g,[s*.11,.60,.29],[.07,.20,.07],[0,0,-s*.17]);this.mesh('sphere','black',g,[s*.12,.46,.43],[.026,.026,.018]);}let legs=[];for(let z of [-.22,.18])for(let s of [-1,1]){let leg=new T.Group();leg.position.set(s*.13,.25,z);this.mesh('cyl',dark,leg,[s*.018,-.12,0],[.045,.26,.045]);g.add(leg);legs.push(leg);}this.rod([0,.34,-.25],[isRat?.13:0,isRat?.14:.62,-.55],.035,isRat?'skin':mat,g);g.userData.limbs=legs;if(isRat)g.scale.setScalar(.65);}
  else if(['BLOB','JELLY','PUDDING','FUNGUS','LIGHT','VORTEX'].includes(f)){mat.transparent=true;mat.opacity=.85;mat.roughness=.28;this.mesh('sphere',mat,g,[0,.32,0],[.43,.37,.43]);for(let i=0;i<5;i++)this.mesh('sphere',dark,g,[Math.sin(i*2)*.23,.28,Math.cos(i*2)*.23],[.12,.15,.1]);if(f==='FUNGUS'){this.mesh('cyl','bone',g,[0,.25,0],[.12,.5,.12]);this.mesh('sphere',mat,g,[0,.57,0],[.43,.15,.43]);}}
  else if(['BAT','BIRD'].includes(f)){this.mesh('sphere',mat,g,[0,.65,0],[.13,.2,.14]);let wings=[];for(let s of [-1,1]){let shape=new T.Shape();shape.moveTo(0,0);shape.lineTo(s*.53,.15);shape.lineTo(s*.4,-.25);shape.lineTo(s*.2,-.1);shape.closePath();let wing=this.mesh(new T.ShapeGeometry(shape),new T.MeshStandardMaterial({color,side:T.DoubleSide,roughness:.9}),g,[s*.07,.7,0]);wings.push(wing);}g.userData.wings=wings;}
  else if(f==='ANT'){for(let z of [-.25,0,.25])this.mesh('sphere',mat,g,[0,.21,z],[.14,.16,.19]);for(let s of [-1,1])for(let z of [-.2,0,.2]){this.rod([0,.22,z],[s*.32,.20,z+.08],.022,dark,g);this.rod([s*.32,.20,z+.08],[s*.40,.015,z+.15],.022,dark,g);}for(let s of [-1,1])this.rod([s*.06,.30,.34],[s*.14,.45,.48],.014,dark,g);}
  else if(['SNAKE','NAGA','WORM'].includes(f)){let pts=[];for(let i=0;i<10;i++)pts.push(new T.Vector3(Math.sin(i*.8)*.18,.1+i*.015,(i-5)*.085));this.mesh(new T.TubeGeometry(new T.CatmullRomCurve3(pts),28,.085,8,false),mat,g);this.mesh('sphere',mat,g,[pts[9].x,.3,pts[9].z],[.13,.12,.14]);}
  else if(f==='DRAGON'){g=this.creature('large dog');g.scale.setScalar(1.75);for(let s of [-1,1]){let sh=new T.Shape();sh.moveTo(0,0);sh.lineTo(s*.72,.6);sh.lineTo(s*.62,-.25);sh.closePath();this.mesh(new T.ShapeGeometry(sh),new T.MeshStandardMaterial({color,side:T.DoubleSide}),g,[s*.13,.6,0]);}}
  else g=this.humanoid(kind,color);if(d.size==='LARGE'&&!['DRAGON','WORM'].includes(f))g.scale.multiplyScalar(1.2);if(d.size==='HUGE'||d.size==='GIGANTIC')g.scale.multiplyScalar(1.6);if(d.size==='SMALL'&&['GNOME','KOBOLD'].includes(f))g.scale.multiplyScalar(.76);return g;
 }
 itemModel(item){let g=new T.Group(),c=item.category;
  if(c==='gold'){for(let n=0;n<8;n++)this.mesh('cyl','gold',g,[Math.sin(n*2.4)*.12,.025+Math.floor(n/3)*.027,Math.cos(n*2.4)*.11],[.072,.024,.072]);}
  else if(c==='potion'){const colors=[0x799a82,0xb46054,0x7c80b4,0x59a6a1];let mat=new T.MeshStandardMaterial({color:colors[item.id%4],metalness:.25,roughness:.16,transparent:true,opacity:.85});this.mesh('sphere',mat,g,[0,.16,0],[.13,.16,.13]);this.mesh('cyl',mat,g,[0,.31,0],[.052,.13,.052]);this.mesh('cyl','wood',g,[0,.39,0],[.055,.05,.055]);this.mesh('box','bone',g,[0,.18,.12],[.12,.12,.012]);}
  else if(c==='weapon'){this.mesh('box','metal',g,[0,.08,0],[.065,.045,.6],[0,.7,0]);this.mesh('box','gold',g,[-.17,.09,-.18],[.22,.06,.04],[0,.7,0]);this.mesh('cyl','leather',g,[-.22,.08,-.26],[.025,.16,.025],[Math.PI/2,0,-.7]);}
  else if(c==='scroll'){this.mesh('box','bone',g,[0,.07,0],[.25,.03,.3]);for(let z of [-.15,.15])this.mesh('cyl','bone',g,[0,.09,z],[.045,.31,.045],[0,0,Math.PI/2]);for(let j=0;j<4;j++)this.mesh('box','dark',g,[0,.091,(j-1.5)*.04],[.14,.003,.009]);}
  else if(c==='spellbook'){this.mesh('box','cloth',g,[0,.09,0],[.27,.13,.35]);this.mesh('box','bone',g,[.013,.095,0],[.245,.085,.32]);this.mesh('box','gold',g,[0,.165,0],[.035,.012,.36]);}
  else if(c==='food'){this.mesh('sphere',item.corpse?'leather':'wood',g,[0,.11,0],[.23,.10,.16]);if(!item.corpse)this.mesh('box','bone',g,[0,.12,0],[.06,.22,.29],[0,0,.1]);}
  else if(c==='gem'){this.mesh('ico',new T.MeshStandardMaterial({color:0x5a9e9b,metalness:.5,roughness:.1}),g,[0,.13,0],[.12,.15,.12]);}
  else if(c==='ring'||c==='amulet'){this.mesh('torus','gold',g,[0,.05,0],[.12,.12,.12],[Math.PI/2,0,0]);this.mesh('sphere','rune',g,[0,.075,.12],[.042,.045,.03]);}
  else if(c==='wand'){this.mesh('cyl','wood',g,[0,.06,0],[.026,.5,.026],[Math.PI/2,0,.6]);this.mesh('sphere','rune',g,[-.14,.06,.19],[.045,.045,.045]);}
  else if(c==='armor'){this.mesh('sphere','metal',g,[0,.17,0],[.24,.16,.2]);this.mesh('box','leather',g,[0,.22,0],[.39,.03,.05]);}
  else{this.mesh('box','wood',g,[0,.15,0],[.32,.26,.26]);for(let x of [-.11,.11])this.mesh('box','metal',g,[x,.15,0],[.03,.28,.28]);}return g;
 }
 sync(force=false){
  const game=this.game;
  if(this.levelKey!==game.key){this.focus.set(game.player.x,0,game.player.y);this.buildLevel();return;}
  // Terrain changes happen as part of a turn. Do not rebuild an entire level or
  // serialize 1,680 tiles on every UI refresh when the turn is unchanged.
  if(!force&&this.lastStructureCheckTurn!==game.turn){this.lastStructureCheckTurn=game.turn;const structure=this.structureKey();if(structure!==this.structure){this.buildLevel();return;}}
  const dummy=new T.Object3D(),color=new T.Color();
  for(const batch of this.batches){let matrixChanged=false,colorChanged=false;batch.entries.forEach((e,i)=>{const seen=!!e.t.seen,visible=!!e.t.visible;if(force||e.lastSeen!==seen){dummy.position.set(...e.pos);dummy.rotation.set(0,e.rot||0,0);dummy.scale.set(...(seen?e.scale:[0,0,0]));dummy.updateMatrix();batch.mesh.setMatrixAt(i,dummy.matrix);e.lastSeen=seen;matrixChanged=true;}if(force||e.lastVisible!==visible){color.set(e.color);if(!visible)color.multiplyScalar(.27);batch.mesh.setColorAt(i,color);e.lastVisible=visible;colorChanged=true;}});if(matrixChanged)batch.mesh.instanceMatrix.needsUpdate=true;if(colorChanged&&batch.mesh.instanceColor)batch.mesh.instanceColor.needsUpdate=true;}
  const occupiedTiles=new Set([`${game.player.x},${game.player.y}`]);for(const m of game.level.monsters)if(m.hp>0)occupiedTiles.add(`${m.x},${m.y}`);
  const occupancyKey=[...occupiedTiles].sort().join('|');
  if(force||occupancyKey!==this.occupancyKey){for(const o of this.tileObjects){o.group.visible=o.t.seen&&(!o.doorFeature||o.t.type==='door');if(o.group.visible)this.applyStandingFade(o.group,occupiedTiles.has(`${o.group.position.x},${o.group.position.z}`));}this.occupancyKey=occupancyKey;}
  else for(const o of this.tileObjects)if(o.doorFeature)o.group.visible=o.t.seen&&o.t.type==='door';
  const entities=[{...game.player,kind:'hero'},...game.level.monsters],live=new Set();
  for(const e of entities){live.add(e.id);let model=this.models.get(e.id);if(!model||model.kind!==e.kind||(e.id===0&&(model.form!==game.player.form||model.identity!==[game.player.role,game.player.race].join(':')))){if(model)this.scene.remove(model.group);const group=e.id===0?(game.player.form?this.creature(game.player.form):N.buildHero(this,game.player)):this.creature(e.kind);group.position.set(e.x,0,e.y);this.scene.add(group);model={group,kind:e.kind,identity:e.id===0?[game.player.role,game.player.race].join(':'):null,form:e.id===0?game.player.form:null,target:new T.Vector3(e.x,0,e.y),heading:0};this.models.set(e.id,model);}model.target.set(e.x,["up","down","branch"].includes(game.tile(e.x,e.y)?.type)?.19:0,e.y);model.heading=Math.atan2(e.facing?.[0]||0,e.facing?.[1]||1);model.group.visible=e.id===0||!!game.tile(e.x,e.y)?.visible&&(!e.invisible||game.has('see invisible'))||game.has('detection');}
  for(const [id,m] of this.models)if(!live.has(id)){this.scene.remove(m.group);this.models.delete(id);}
  const itemKey=game.level.items.map(o=>`${o.item.id}:${o.item.category}:${o.item.name}:${o.x},${o.y}:${game.tile(o.x,o.y)?.seen?1:0}`).join('|')+'#'+game.level.traps.map(t=>`${t.x},${t.y}:${t.seen?1:0}:${t.type}`).join('|');
  if(force||itemKey!==this.itemSceneKey){
   if(!this.itemGroup)this.itemGroup=new T.Group(),this.world.add(this.itemGroup);
   const removeEntry=entry=>{this.itemGroup.remove(entry.group);entry.group.traverse(o=>{if(o.geometry&&!this.sharedGeometry.has(o.geometry))o.geometry.dispose();});};
   const liveItems=new Set();
   for(const o of game.level.items){if(!game.tile(o.x,o.y)?.seen)continue;const id=o.item.id,signature=o.item.category+':'+o.item.name;liveItems.add(id);let entry=this.itemModels.get(id);if(entry?.signature!==signature){if(entry)removeEntry(entry);entry=null;}
    if(!entry){const g=this.itemModel(o.item);g.position.set(o.x,.015,o.y);g.rotation.y=o.item.id*2.4;g.traverse(child=>{if(!child.material)return;const original=Array.isArray(child.material)?child.material:[child.material],materials=original.map(mat=>mat.clone());child.material=Array.isArray(child.material)?materials:materials[0];for(const mat of materials){mat.transparent=true;mat.depthWrite=true;mat.opacity=1;}});this.itemGroup.add(g);entry={group:g,x:o.x,y:o.y,signature};this.itemModels.set(id,entry);}else{entry.x=o.x;entry.y=o.y;entry.group.position.set(o.x,.015,o.y);}
   }
   for(const [id,entry] of this.itemModels)if(!liveItems.has(id)){removeEntry(entry);this.itemModels.delete(id);}
   const liveTraps=new Set();
   for(const t of game.level.traps){if(!t.seen||!game.tile(t.x,t.y)?.seen)continue;const key=`${t.x},${t.y}:${t.type}`;liveTraps.add(key);let entry=this.trapModels.get(key);if(!entry){const g=new T.Group();g.position.set(t.x,.017,t.y);const ring=new T.Mesh(new T.RingGeometry(.24,.28,8),new T.MeshBasicMaterial({color:0xbe8063,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;g.add(ring);if(t.type==='pit')this.mesh('cyl','black',g,[0,0,0],[.3,.015,.3]);else for(let a=0;a<4;a++)this.mesh('cone','metal',g,[Math.sin(a*Math.PI/2)*.2,.08,Math.cos(a*Math.PI/2)*.2],[.035,.16,.035]);this.itemGroup.add(g);entry={group:g,x:t.x,y:t.y};this.trapModels.set(key,entry);}}
   for(const [key,entry] of this.trapModels)if(!liveTraps.has(key)){removeEntry(entry);this.trapModels.delete(key);}
   this.itemEntries=[...this.itemModels.values(),...this.trapModels.values()];this.itemSceneKey=itemKey;
  }
  for(const e of this.itemEntries)this.applyStandingFade(e.group,occupiedTiles.has(`${e.x},${e.y}`));
  this.lastTurn=game.turn;
 }
 applyStandingFade(group,fade){
  // Hidden room decorations are revealed frequently. Do not clone all of their
  // shared materials just because they became visible; only materialize the
  // per-group fade when the player is actually standing on that tile.
  if(!fade&&!group.userData.standingFadeMaterialized)return;
  group.traverse(child=>{if(child.material){const original=Array.isArray(child.material)?child.material:[child.material],materials=original.map(mat=>{if(!mat.userData)mat.userData={};if(mat.userData.standingFadeMaterial)return mat;const clone=mat.clone();clone.userData={...(clone.userData||{}),standingFadeMaterial:true,standingFadeBaseOpacity:mat.opacity??1,standingFadeBaseDepthWrite:mat.depthWrite};return clone;});child.material=Array.isArray(child.material)?materials:materials[0];for(const mat of materials){mat.transparent=true;mat.depthWrite=fade?false:mat.userData.standingFadeBaseDepthWrite;mat.opacity=mat.userData.standingFadeBaseOpacity*(fade?.42:1);}}if(child.isLight){if(child.userData.standingFadeBaseIntensity===undefined)child.userData.standingFadeBaseIntensity=child.intensity;child.intensity=child.userData.standingFadeBaseIntensity*(fade?.42:1);}});group.userData.standingFadeMaterialized=true;group.userData.standingFade=fade;
 }
 event(e){if(['hit','hurt','miss'].includes(e.type)){if(e.type==='hurt')this.shake=.13;let model=this.models.get(e.id||0);if(model)model.attackUntil=performance.now()+260;this.particles(e.x,e.y,e.type==='hurt'?0xb4372d:e.type==='hit'?0xdbaa69:0xb9c2c5,10);}
  if(e.type==='kill')this.particles(e.x,e.y,0xbda084,20);if(['magic','levelup'].includes(e.type))this.particles(e.x??this.game.player.x,e.y??this.game.player.y,0x80d7ce,28);
  if(e.type==='beam'&&e.points?.length){let pts=e.points.map(p=>new T.Vector3(p.x,.45,p.y));if(pts.length<2)pts.unshift(new T.Vector3(this.game.player.x,.45,this.game.player.y));let g=new T.BufferGeometry().setFromPoints(pts),m=new T.Line(g,new T.LineBasicMaterial({color:e.name==='fire'?0xff993d:0x90dce7,transparent:true,opacity:1}));this.scene.add(m);this.effects.push({mesh:m,life:.38,max:.38});}
 }
 particles(x,y,color,count){if(x==null)return;let a=new Float32Array(count*3),v=[];for(let i=0;i<count;i++){a[i*3]=x;a[i*3+1]=.6;a[i*3+2]=y;v.push([(Math.random()-.5)*2,Math.random()*2,(Math.random()-.5)*2]);}let g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(a,3));let m=new T.Points(g,new T.PointsMaterial({color,size:.055,transparent:true,opacity:1}));this.scene.add(m);this.effects.push({mesh:m,life:.7,max:.7,velocity:v});}
 resize(){let w=this.canvas.clientWidth,h=this.canvas.clientHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 hover(e){const p=this.pick(e);this.hoverTile=p;if(p){this.cursor.position.set(p.x,.024,p.y);this.cursor.visible=!!this.game.tile(p.x,p.y)?.seen;}else this.cursor.visible=false;}
 pick(e){const r=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);let p=new T.Vector3();if(this.raycaster.ray.intersectPlane(new T.Plane(new T.Vector3(0,1,0),0),p)){let x=Math.round(p.x),y=Math.round(p.z);return this.game.tile(x,y)?{x,y}:null;}return null;}
 animate(){this.raf=requestAnimationFrame(this.animate);let dt=Math.min(.05,this.clock.getDelta()),time=this.clock.elapsedTime,game=this.game,now=performance.now();if(this.lastTurn!==game.turn||this.levelKey!==game.key)this.sync();let hero=this.models.get(0);
  for(let [id,m]of this.models){let distance=m.group.position.distanceTo(m.target),moving=distance>.015;m.group.position.lerp(m.target,1-Math.exp(-dt*14));let delta=Math.atan2(Math.sin(m.heading-m.group.rotation.y),Math.cos(m.heading-m.group.rotation.y));m.group.rotation.y+=delta*(1-Math.exp(-dt*15));let u=m.group.userData;if(u.body)u.body.position.y=(moving?Math.abs(Math.sin(time*13))*.025:Math.sin(time*2)*.007);if(u.limbs)u.limbs.forEach((l,i)=>l.rotation.x=Math.sin(time*14+(i%2)*Math.PI)*(moving?.45:.018));if(u.wings)u.wings.forEach((w,i)=>w.rotation.y=Math.sin(time*12)*(i?1:-1)*.6);if(u.weapon&&m.attackUntil>now)u.weapon.rotation.x=-Math.sin((m.attackUntil-now)/260*Math.PI)*1.5;if(u.cape){let a=u.cape.geometry.attributes.position,o=u.cape.userData.original;for(let i=0;i<a.count;i++){let v=(.34-o[i*3+1])/.68;a.setZ(i,o[i*3+2]+Math.sin(time*3+o[i*3]*4)*.025*v+(moving?Math.sin(time*10)*.045*v:0));}a.needsUpdate=true;}}
  if(hero){this.focus.lerp(hero.group.position,1-Math.exp(-dt*7));this.heroRing.position.set(hero.group.position.x,hero.group.position.y+.021,hero.group.position.z);this.reusableOffset.set(-.3,2,.1);this.playerLight.position.copy(hero.group.position).add(this.reusableOffset);}
  this.zoom+=(this.targetZoom-this.zoom)*(1-Math.exp(-dt*7));this.angle+=(this.targetAngle-this.angle)*(1-Math.exp(-dt*6));let horizontal=this.zoom*.66;const rightOffset=window.innerWidth>1100?1.9:.5;
  this.reusableLook.copy(this.focus).add(this.reusableOffset.set(rightOffset,0,-.25));const look=this.reusableLook;this.camera.position.set(look.x+Math.sin(this.angle)*horizontal,look.y+this.zoom*.86,look.z+Math.cos(this.angle)*horizontal);this.shake*=Math.exp(-dt*10);this.camera.position.x+=(Math.random()-.5)*this.shake;this.camera.lookAt(look);this.reusableOffset.set(-6,15,-6);this.sun.position.copy(this.focus).add(this.reusableOffset);this.sun.target.position.copy(this.focus);
  const closest=[];for(const torch of this.torches){if(!torch.t.seen)continue;let d=torch.group.position.distanceToSquared(this.focus),insert=closest.findIndex(x=>d<x.d);if(insert<0){if(closest.length<6)closest.push({torch,d});}else{closest.splice(insert,0,{torch,d});if(closest.length>6)closest.pop();}}this.lights.forEach((light,i)=>{const t=closest[i]?.torch;light.visible=!!t;if(t){this.reusableOffset.set(0,1.2,0);light.position.copy(t.group.position).add(this.reusableOffset);light.intensity=(24+Math.sin(time*11+t.phase)*3+Math.sin(time*17+t.phase)*2)*(t.t.visible?1:.35);}});
  for(let t of this.torches){let f=1+Math.sin(time*13+t.phase)*.09+Math.sin(time*21)*.04;t.mesh.scale.y=t.scale*f;t.mesh.position.x=Math.sin(time*9+t.phase)*.02;t.halo.material.opacity=.65+Math.sin(time*8+t.phase)*.1;}
  this.mats.water.color.setHSL(.51,.44,.27+Math.sin(time*2)*.018);for(let n=this.effects.length-1;n>=0;n--){let e=this.effects[n];e.life-=dt;e.mesh.material.opacity=Math.max(0,e.life/e.max);if(e.velocity){let a=e.mesh.geometry.attributes.position;for(let i=0;i<a.count;i++){let v=e.velocity[i];v[1]-=dt*3;a.setXYZ(i,a.getX(i)+v[0]*dt,a.getY(i)+v[1]*dt,a.getZ(i)+v[2]*dt);}a.needsUpdate=true;}if(e.life<=0){this.scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();this.effects.splice(n,1);}}
  this.renderer.render(this.scene,this.camera);this.fps=1/dt;
 }
 setQuality(q){this.quality=q;this.renderer.setPixelRatio(q==='low'?1:Math.min(devicePixelRatio,1.5));this.renderer.shadowMap.enabled=q!=='low';this.resize();}
}
N.Renderer=Renderer;
})();
