(() => {
'use strict';
const N=globalThis.NH,$=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon={weapon:')',armor:'[',food:'%',potion:'!',scroll:'?',wand:'/',ring:'=',amulet:'"',spellbook:'+',tool:'(',gem:'*',gold:'$'};
const np={'1':[-1,1],'2':[0,1],'3':[1,1],'4':[-1,0],'6':[1,0],'7':[-1,-1],'8':[0,-1],'9':[1,-1]},vi={y:[-1,-1],k:[0,-1],u:[1,-1],h:[-1,0],l:[1,0],b:[-1,1],j:[0,1],n:[1,1]},arrows={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]};
const selfMagic=new Set(['healing','extra healing','full healing','cure sickness','cure blindness','light','detect monsters','detect food','detect treasure','detect unseen','identify','magic mapping','remove curse','haste self','levitation','invisibility','protection','restore ability','create monster','create familiar','clairvoyance','cause fear','charm monster']);
class UI {
 constructor(){this.game=new N.Game('MENACE-366','Knight','Adventurer');this.numberPad=true;this.modal=null;this.direction=null;this.prefix=null;this.noticeRunPrefix=false;this.counter=null;this.lastInput=0;this.audio=new N.AudioEngine();this.renderer=new N.Renderer($('world'),this.game);this.runTimer=null;this.mapMode=false;this.lastLog='';this.pendingEvents=[];this.bind();this.refresh();this.toastTimer=null;this.suspended=false;this.ended=false;this.frame=setInterval(()=>this.updateHover(),120);this.started=false;this.config={...N.defaults};this.loadPreferences();this.mainMenu();}
 bind(){document.addEventListener('keydown',e=>this.key(e));document.addEventListener('pointerdown',()=>this.audio.start(),{once:true});document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>this.command(b.dataset.command)));$('brand').onclick=()=>this.mainMenu();$('sound').onclick=()=>{this.audio.start();this.audio.toggle();$('sound').style.opacity=this.audio.enabled?'1':'.35';this.toast('Sound '+(this.audio.enabled?'enabled':'muted'));};$('modal-close').onclick=()=>this.close();$('modal-backdrop').onclick=e=>{if(e.target===$('modal-backdrop')&&!this.suspended&&!this.game.dead)this.close();};$('world').addEventListener('click',e=>{if(this.modal||this.suspended)return;this.audio.start();const t=this.renderer.pick(e);if(!t||!this.game.tile(t.x,t.y)?.seen)return;const dx=t.x-this.game.player.x,dy=t.y-this.game.player.y;if(this.direction){if(Math.max(Math.abs(dx),Math.abs(dy))<=1)this.resolveDirection([Math.sign(dx),Math.sign(dy)]);return;}if(this.inspect){this.inspectTile(t);return;}if(Math.max(Math.abs(dx),Math.abs(dy))===1){if(!this.canAct())return;this.game.move(dx,dy);this.refresh();}else if(!dx&&!dy){this.game.look();this.refresh();}else this.travel(t);});window.addEventListener('beforeunload',()=>{if(this.game.turn>1&&!this.game.dead&&!this.game.won){try{localStorage.setItem('nethack3d-recovery',this.game.serialize());}catch{}}});}
 key(e){if(['Shift','Control','Alt','Meta','CapsLock','NumLock','ScrollLock'].includes(e.key)||e.altKey||e.metaKey)return;const target=e.target.tagName;if(['INPUT','SELECT','TEXTAREA'].includes(target)){if(e.key==='Escape'){e.preventDefault();this.close();}return;}
  this.audio.start();if(e.key==='Escape'){e.preventDefault();this.stopRun();if(this.modal)this.close();else if(this.direction||this.prefix||this.counter!==null||this.inspect)this.cancel();else this.pause();return;}
  if(this.modal){if(this.modal.onKey){e.preventDefault();this.modal.onKey(e.key,e);}return;}if(this.suspended)return;
  let key=e.key,code=e.code,dir=code.startsWith('Numpad')?np[code.slice(6)]:arrows[key]||(this.numberPad?np[key]:vi[key.toLowerCase()]);if(e.ctrlKey){const k=key.toLowerCase();if(k==='d'){e.preventDefault();this.command('kick');}else if(k==='p'){e.preventDefault();this.chronicle();}else if(k==='x'){e.preventDefault();this.attributes();}else if(k==='o'){e.preventDefault();this.overview();}else if(k==='s'){e.preventDefault();this.save();}return;}
  if(this.counter!==null&&/^\d$/.test(key)&&!code.startsWith('Numpad')){e.preventDefault();this.counter=(this.counter+key).slice(0,3);this.prompt('Repeat count: '+(this.counter||'…')+' · enter a command');return;}
  if(dir){e.preventDefault();if(e.repeat&&performance.now()-this.lastInput<125)return;this.lastInput=performance.now();if(this.direction){this.resolveDirection(dir);return;}if(this.inspect){const pos=this.inspect;pos.x=Math.max(0,Math.min(79,pos.x+dir[0]));pos.y=Math.max(0,Math.min(20,pos.y+dir[1]));this.renderer.cursor.position.set(pos.x,.03,pos.y);this.renderer.cursor.visible=true;this.prompt(this.describe(pos)+' · Enter to inspect');return;}if(this.noticeRunPrefix){this.noticeRunPrefix=false;this.clearPrompt();this.run(dir,false,true);return;}const mode=this.prefix;this.prefix=null;this.clearPrompt();if(mode==='g'||mode==='G'||mode==='M'||e.shiftKey){this.run(dir,mode==='M');return;}this.stopRun();if(!this.canAct())return;this.game.move(...dir,mode==='m'?'safe':mode==='F'?'fight':'normal');this.refresh();return;}
  if(code==='Numpad5'||(key==='5'&&this.numberPad)){e.preventDefault();if(this.direction){this.resolveDirection([0,0]);return;}this.stopRun();this.noticeRunPrefix=true;this.prompt('Move until something is noticed · choose a direction');return;}
  if(code==='NumpadDecimal'||(key==='5'&&!this.numberPad)){e.preventDefault();this.command('.');return;}
  if(this.inspect&&(key==='Enter'||key==='.'||key===';')){e.preventDefault();this.inspectTile(this.inspect);return;}
  if(key===' '){e.preventDefault();return;}if(e.repeat)return;e.preventDefault();this.command(key);
 }
 canAct(){if(this.started===false||this.modal||this.suspended)return false;if(this.game.dead||this.game.won){this.endScreen();return false;}if(this.game.player.status.paralysis){this.game.log('You cannot move!','warning');this.game.endTurn();this.refresh();return false;}return true;}
 command(key){if(this.started===false){if(key==='O')this.options();else if(key==='?')this.help();return;}if(this.modal&&!['i','?','O','V','+','Tab'].includes(key))return;this.stopRun();this.noticeRunPrefix=false;if(this.direction){this.toast('Choose a direction, or press Escape to cancel.');return;}
  if(['i','I'].includes(key)){this.inventory();return;}if(key==='?'||key==='&'||key==='h'&&this.numberPad){this.help();return;}if(key==='O'){this.options();return;}if(key==='V'){this.chronicle();return;}if(key==='+'){this.spells(false);return;}if(key==='Tab'){this.map();return;}if(key==='S'){this.save();return;}if(key==='v'){this.about();return;}if(key==='@'){this.game.autopickup=!this.game.autopickup;this.toast('Autopickup '+(this.game.autopickup?'on':'off'));return;}if(key===':'){this.game.look();this.refresh();return;}if(key==='/'||key===';'){this.inspect={x:this.game.player.x,y:this.game.player.y};this.prompt('Inspect · choose a tile with numpad or mouse · Enter to examine');return;}if(key==='$'){this.toast(`You have ${this.game.player.gold} gold pieces.`);return;}
  if(!this.canAct())return;const count=Number(this.counter||1);this.counter=null;this.clearPrompt();if(count>1&&['s','.'].includes(key)){this.repeatAction(key,count);return;}
  switch(key){case'.':this.game.wait();break;case',':this.game.pickup();break;case's':this.game.search();break;case'o':this.askDirection('Open which door?',d=>this.game.door(...d,'open'));return;case'c':this.askDirection('Close which door?',d=>this.game.door(...d,'close'));return;case'k':case'kick':this.askDirection('Kick in which direction?',d=>this.game.door(...d,'kick'));return;
   case'd':case'D':this.selectItem('Drop an item',()=>true,i=>this.game.drop(i));return;
   case'w':this.selectItem('Wield a weapon',()=>true,i=>this.game.equip(i,'weapon'));return;
   case'W':this.selectItem('Wear armor',i=>i.category==='armor',i=>this.game.equip(i));return;
   case'P':this.selectItem('Put on an accessory',i=>['ring','amulet'].includes(i.category),i=>this.game.equip(i));return;
   case'T':case'R':case'A':this.selectItem('Remove equipment',i=>Object.values(this.game.player.equipment).includes(i.id),i=>this.game.unequip(i));return;
   case'e':{const food=this.game.level.items.find(o=>N.distance(o,this.game.player)===0&&o.item.category==='food');if(food){this.show('Eat from the floor','A MOMENT OF SUSTENANCE',`<p class="modal-copy">Eat ${esc(this.game.label(food.item))}?</p>`,[{text:'Eat [y]',action:()=>{let i=food.item;let added=this.game.addItem(i);if(added){this.game.level.items=this.game.level.items.filter(o=>o!==food);this.close();this.game.eat(added);this.refresh();}}},{text:'Inventory [n]',action:()=>this.selectItem('Eat something',i=>i.category==='food',i=>this.game.eat(i))}]);this.modal.onKey=k=>{if(k==='y')$('modal-foot').children[0].click();if(k==='n')$('modal-foot').children[1].click();};}else this.selectItem('Eat something',i=>i.category==='food',i=>this.game.eat(i));return;}
   case'q':if(this.game.tile(this.game.player.x,this.game.player.y).type==='fountain'){this.show('The bubbling fountain','QUAFF',`<p class="modal-copy">Drink from the fountain, or choose a potion from your inventory?</p>`,[{text:'Drink water [y]',action:()=>{this.close();this.game.drinkFountain();this.refresh();}},{text:'Choose a potion [n]',action:()=>this.selectItem('Quaff a potion',i=>i.category==='potion',i=>this.game.quaff(i))}]);this.modal.onKey=k=>{if(k==='y')$('modal-foot').children[0].click();if(k==='n')$('modal-foot').children[1].click();};}else this.selectItem('Quaff a potion',i=>i.category==='potion',i=>this.game.quaff(i));return;
   case'r':this.selectItem('Read a scroll or spellbook',i=>['scroll','spellbook'].includes(i.category),i=>this.game.read(i));return;
   case'z':this.selectItem('Zap a wand',i=>i.category==='wand',i=>{if(this.game.def(i).direction==='NODIR')this.game.zap(i,null);else this.askDirection('Zap '+this.game.label(i)+' in which direction?',d=>this.game.zap(i,d));});return;
   case'Z':this.spells(true);return;
   case't':this.selectItem('Throw an object',()=>true,i=>this.askDirection('Throw in which direction?',d=>this.game.throwItem(i,d)));return;
   case'Q':this.selectItem('Ready your quiver',()=>true,i=>{this.game.player.equipment.quiver=i.id;this.game.log(`You ready ${this.game.label(i)}.`);});return;
   case'f':{let i=this.game.player.inventory.find(i=>i.id===this.game.player.equipment.quiver);if(!i)i=this.game.player.inventory.find(i=>this.game.def(i).ammo||['dart','dagger','ya','shuriken'].includes(i.name));if(i)this.askDirection('Fire in which direction?',d=>this.game.throwItem(i,d));else{this.game.log('You have no ammunition ready. Use Q to select a quiver.');this.refresh();}return;}
   case'a':this.selectItem('Apply a tool',i=>i.category==='tool',i=>{if(i.contents){this.containerMenu(i);return;}if(['skeleton key','lock pick','credit card','pick-axe','mirror','stethoscope','leash','saddle','grappling hook','fire horn','frost horn'].includes(i.name))this.askDirection('Apply '+i.name+' in which direction?',d=>this.game.apply(i,d));else this.game.apply(i);});return;
   case'p':this.game.pay();break;case'<':this.game.stairs(-1);break;case'>':this.game.stairs(1);break;case'E':this.textPrompt('Write in the dust','ENGRAVE','What do you want to write?','',text=>{this.game.engrave(text);this.refresh();});return;
   case'#':this.extended();return;case'm':case'F':case'g':case'G':case'M':this.prefix=key;this.prompt(({m:'Move without fighting or picking up',F:'Force fight',g:'Run',G:'Run',M:'Run without pickup'})[key]+' · choose a direction');return;
   case'n':this.counter='';this.prompt('Repeat count · type a number, then a command (n10s)');return;
   case'_':this.toast('Click an explored tile to travel. Travel stops when danger appears.');return;
   case'x':this.game.swapWeapons();break;
   case'\\':this.discoveries();return;case')':case'[':case'=':case'"':this.attributes();return;
   default:this.toast(`Unbound command “${key}”. Press ? for controls.`);return;
  }this.refresh();
 }
 refresh(){const g=this.game,p=g.player;this.renderer.game=g;this.renderer.sync();$('hero-name').textContent=p.name;$('role-name').textContent=p.role;$('hero-level').textContent=p.level;$('hp-value').textContent=`${Math.max(0,p.hp)} / ${p.maxHp}`;$('pw-value').textContent=`${p.pw} / ${p.maxPw}`;$('hp-bar').style.width=Math.max(0,p.hp/p.maxHp*100)+'%';$('pw-bar').style.width=(p.maxPw?p.pw/p.maxPw*100:0)+'%';$('ac').textContent=g.ac;$('gold').textContent=p.gold.toLocaleString();$('xp').textContent=p.xp+' / '+(p.level<10?10*2**p.level:10000*(p.level-8));$('condition').textContent=Object.keys(p.status).filter(k=>!['light','detection','protection'].includes(k))[0]||g.encumbrance||g.hunger;$('alignment').textContent=p.align.toUpperCase()+' · '+p.race.toUpperCase();$('location').textContent=g.branch==='Mines'?'The Gnomish Mines':'The Dungeons of Doom';$('depth').textContent=`DEPTH ${String(g.depth).padStart(2,'0')} · ${g.branch==='Mines'?'BENEATH THE MOUNTAIN':'THE MAZES OF MENACE'}`;$('turn-label').textContent='TURN '+g.turn.toLocaleString();
  $('messages').innerHTML=g.messages.slice(-4).map(m=>`<div class="${m.type}"><span class="turn">${String(m.turn).padStart(3,'0')}</span>${esc(m.text)}</div>`).join('');
  const nearby=g.level.monsters.filter(m=>g.tile(m.x,m.y)?.visible).sort((a,b)=>Number(!!b.tame)-Number(!!a.tame)||N.distance(a,p)-N.distance(b,p));$('nearby-count').textContent=String(nearby.length).padStart(2,'0');$('nearby').innerHTML=nearby.slice(0,4).map(m=>`<div class="nearby-entity"><span class="entity-symbol ${m.tame||m.peaceful?'':'hostile'}">${m.tame?'d':esc(({ORC:'o',GNOME:'G',DOG:'d',RODENT:'r',ANT:'a',BAT:'B',FELINE:'f',KOBOLD:'k',HUMAN:'@'})[N.monsterDef(m.kind)?.family]||m.kind[0])}</span><span class="entity-name">${esc(m.name||m.kind[0].toUpperCase()+m.kind.slice(1))}<small>${m.tame?'LOYAL COMPANION':m.peaceful?'PEACEFUL':'HOSTILE'}</small></span><span class="entity-distance">${N.distance(m,p)} SQ</span></div>`).join('')||'<p class="empty-state">All is quiet. For now.</p>';
  $('quest-step').textContent=p.inventory.some(i=>i.name==='Amulet of Yendor')?'Return to the surface with the Amulet':g.depth===1?'Find the staircase to the next level':'Continue your descent into the unknown';this.drawMap($('minimap'));
  const events=g.events.splice(0);for(let e of events){this.renderer.event(e);this.audio.play(e.type);if(e.type==='hurt')this.stopRun();if(e.type==='stairs'){let el=$('floor-title');el.innerHTML=`<small>THE JOURNEY CONTINUES</small><h1>${esc($('location').textContent)}</h1><span>DEPTH ${g.depth}</span>`;el.style.animation='none';void el.offsetWidth;el.style.animation='titlefade 5s forwards';}if(e.type==='branchport'){const branches=[...new Set(Object.values(g.levels).map(l=>l.branch))].filter(b=>['Dungeons','Mines','Sokoban','Quest'].includes(b));this.show('Choose a known branch','ARTIFACT PORTAL','<p class="modal-copy">The Eye opens a way to a place you have visited.</p>',branches.map(b=>({text:N.branches[b].name,action:()=>{this.close();g.changeLevel(b,1,null);this.refresh();}})));}if(e.type==='container'){const i=g.allInventory().find(i=>i.id===e.id);if(i)this.containerMenu(i);}if(e.type==='toolTarget'){const tool=g.allInventory().find(i=>i.id===e.id);this.selectItem('Grease an object',i=>i!==tool,i=>g.apply(tool,[0,0],i));}if(e.type==='write'){const tool=g.allInventory().find(i=>i.id===e.id);this.textPrompt('Write with your marker','INSCRIBE','Name of a known scroll','',name=>{g.apply(tool,[0,0],{name,category:'scroll'});this.refresh();});}if(e.type==='wishing')setTimeout(()=>this.wish(),50);if(e.type==='genocide')setTimeout(()=>this.genocide(),50);}
  if((g.dead||g.won)&&!this.ended){this.ended=true;this.stopRun();setTimeout(()=>this.endScreen(),500);}
 }
 drawMap(canvas,full=false){let g=this.game,l=g.level,ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#111b1d';ctx.fillRect(0,0,W,H);let seen=l.tiles.flat().filter(t=>t.seen&&t.type!=='rock'),minX=full?0:Math.max(0,Math.min(...seen.map(t=>t.x))-3),maxX=full?79:Math.min(79,Math.max(...seen.map(t=>t.x))+3),minY=full?0:Math.max(0,Math.min(...seen.map(t=>t.y))-2),maxY=full?20:Math.min(20,Math.max(...seen.map(t=>t.y))+2);const size=Math.min((W-20)/(maxX-minX+1),(H-20)/(maxY-minY+1)),ox=(W-size*(maxX-minX+1))/2,oy=(H-size*(maxY-minY+1))/2;
  for(let t of seen){ctx.fillStyle=['wall','secret'].includes(t.type)?'#45514b':t.visible?'#7a8670':'#394a42';if(t.type==='door')ctx.fillStyle='#b49a62';if(t.type==='water'||t.type==='fountain')ctx.fillStyle='#518a8a';ctx.fillRect(ox+(t.x-minX)*size,oy+(t.y-minY)*size,Math.max(1,size-1),Math.max(1,size-1));if(['up','down','branch'].includes(t.type)){ctx.fillStyle='#d4bb7f';ctx.font=`bold ${Math.max(8,size)}px monospace`;ctx.fillText(t.type==='up'?'<':'>',ox+(t.x-minX)*size,oy+(t.y-minY+1)*size);}}
  for(let m of l.monsters){if(!g.tile(m.x,m.y)?.visible&&!g.has('detection'))continue;ctx.fillStyle=m.tame?'#9eb88b':m.peaceful?'#8aabb3':'#c77b61';ctx.beginPath();ctx.arc(ox+(m.x-minX+.5)*size,oy+(m.y-minY+.5)*size,Math.max(2,size*.25),0,Math.PI*2);ctx.fill();}
  ctx.fillStyle='#f1ce84';ctx.shadowColor='#efb14e';ctx.shadowBlur=7;ctx.fillRect(ox+(g.player.x-minX)*size,oy+(g.player.y-minY)*size,size-1,size-1);ctx.shadowBlur=0;let total=l.tiles.flat().filter(t=>t.type!=='rock').length;$('explored').textContent=Math.round(seen.length/total*100)+'% EXPLORED';}
 updateHover(){if(this.modal)return;let t=this.renderer.hoverTile;const label=$('hover-label');if(t&&this.game.tile(t.x,t.y)?.seen){label.textContent=this.describe(t);label.hidden=false;}else label.hidden=true;}
 describe(t){let tile=this.game.tile(t.x,t.y);if(!tile?.seen)return'Unexplored';let m=this.game.monsterAt(t.x,t.y);if(m&&tile.visible)return(m.name||m.kind)+(m.tame?' · tame':m.peaceful?' · peaceful':' · hostile');let i=this.game.level.items.find(o=>N.distance(o,t)===0);if(i)return this.game.label(i.item);return({up:'Stairs up',down:'Stairs down',branch:'Stairs to the Gnomish Mines',fountain:'Bubbling fountain',altar:'Ancient altar',door:tile.locked?'Locked door':'Closed door',secret:'Stone wall',wall:'Stone wall',floor:'Stone floor',corridor:'Dark corridor',openDoor:'Open doorway'})[tile.type]||tile.type;}
 inspectTile(t){this.inspect=null;this.clearPrompt();const g=this.game,m=g.monsterAt(t.x,t.y),d=m&&g.tile(t.x,t.y)?.visible&&N.monsterDef(m.kind);if(d){this.show(m.name||m.kind,'EXAMINE',`<p class="modal-copy">${m.tame?'Your loyal companion.':m.peaceful?'This creature regards you peacefully.':'A hostile creature watches you from the dungeon.'}</p><div class="stats-grid"><div class="stat-card"><strong>${d.level}</strong><small>BASE LEVEL</small></div><div class="stat-card"><strong>${d.ac}</strong><small>ARMOR CLASS</small></div><div class="stat-card"><strong>${d.speed}</strong><small>MOVEMENT RATE</small></div></div><p class="modal-copy">Attacks: ${d.attacks.map(a=>`${esc(a.type.toLowerCase())} ${a.dice}d${a.sides} (${esc(a.effect.toLowerCase())})`).join(', ')||'none'}.</p><p class="modal-copy">${d.resists.length?'Resistances: '+esc(d.resists.map(r=>r.replace('MR_','').toLowerCase()).join(', ')):''}</p>`,[]);}else this.toast(this.describe(t));}
 prompt(text){$('prompt-text').textContent=text;$('prompt').hidden=false;}
 clearPrompt(){$('prompt').hidden=true;}
  cancel(){this.direction=null;this.prefix=null;this.noticeRunPrefix=false;this.counter=null;this.inspect=null;this.clearPrompt();this.stopRun();}
 askDirection(text,fn){this.close();this.direction={fn};this.prompt(text+' · numpad / arrows');}
 resolveDirection(dir){let fn=this.direction.fn;this.direction=null;this.clearPrompt();if(!dir[0]&&!dir[1]){this.toast('Choose an adjacent direction.');return;}if(this.canAct())fn(dir);this.refresh();}
 show(title,eyebrow,body,buttons=[]){this.stopRun();this.modal={};$('modal-title').textContent=title;$('modal-eyebrow').textContent=eyebrow;$('modal-body').innerHTML=body;$('modal-foot').innerHTML='';for(let [n,b]of buttons.entries()){let button=document.createElement('button');button.className=n===0?'primary-button':'secondary-button';button.textContent=b.text;button.onclick=b.action;$('modal-foot').appendChild(button);}if(!buttons.length)$('modal-foot').innerHTML='<span>Time stands still while this menu is open.</span><span style="margin-left:auto"><kbd>ESC</kbd> Back to the dungeon</span>';$('modal-backdrop').hidden=false;$('modal-close').hidden=false;$('modal-body').scrollTop=0;setTimeout(()=>($('modal-body').querySelector('input')||$('modal-close')).focus(),0);}
 close(){if(this.suspended){this.toast('Resume your saved journey to continue.');return;}this.modal=null;$('modal-backdrop').hidden=true;$('world').focus();}
 toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>$('toast').hidden=true,2800);}
 selectItem(title,filter,fn){let list=this.game.player.inventory.filter(filter);this.show(title,'INVENTORY · SELECT BY LETTER',this.inventoryRows(list),[]);const select=i=>{this.close();fn(i);this.refresh();};this.wireItems(list,select);this.modal.onKey=k=>{let i=list.find(i=>i.letter===k);if(i)select(i);};}
 inventoryRows(list){return `<div class="inventory-summary"><span>${list.length} ITEMS</span><span>${this.game.weight} / ${this.game.capacity} WEIGHT ${esc(this.game.encumbrance)}</span></div>`+(list.map(i=>{let slot=Object.keys(this.game.player.equipment).find(k=>this.game.player.equipment[k]===i.id);return`<button class="inventory-row" data-item="${i.id}"><kbd>${i.letter}</kbd><span class="item-icon">${esc(icon[i.category]||'(')}</span><span class="item-name">${esc(this.game.label(i))}<span class="item-note">${slot?(slot==='weapon'?'WIELDED':slot==='quiver'?'QUIVERED':'WORN · '+slot.toUpperCase()):i.unpaid?'UNPAID · '+i.price+' GOLD':''}</span></span><span class="item-weight">${this.game.itemWeight(i)} wt</span></button>`;}).join('')||'<div class="empty-state">You have no matching items.</div>');}
 wireItems(list,fn){$('modal-body').querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>fn(list.find(i=>i.id===Number(b.dataset.item))));}
 inventory(){const list=this.game.player.inventory;this.show('Your inventory','PACK & EQUIPMENT',this.inventoryRows(list),[{text:'Character attributes',action:()=>this.attributes()},{text:'Discovered items',action:()=>this.discoveries()}]);this.wireItems(list,i=>this.itemDetail(i));this.modal.onKey=k=>{let i=list.find(i=>i.letter===k);if(i)this.itemDetail(i);};}
 itemDetail(i){const g=this.game,d=g.def(i),known=i.known||g.identified[i.category+':'+i.name]||d.known,slot=Object.keys(g.player.equipment).find(k=>g.player.equipment[k]===i.id);let details=`${i.category[0].toUpperCase()+i.category.slice(1)} · ${d.weight||0} weight each`;if(known&&d.damage)details+=` · 1d${d.damage} base damage`;if(known&&d.ac)details+=` · ${d.ac+(i.enchant||0)} armor protection`;if(known&&i.category==='wand')details+=` · ${i.charges} charges`;this.show(g.label(i),'ITEM '+i.letter.toUpperCase(),`<div class="item-detail"><h3>${esc(details)}</h3><p>${known?'You recognize this item.':'The true nature of this item remains unknown. Appearances are randomized for each journey.'}</p><p>${i.bucKnown?(i.buc<0?'This item is cursed.':i.buc>0?'This item is blessed.':'This item is uncursed.'):'Its blessing or curse status is unknown.'}</p>${slot?'<p>Currently '+esc(slot==='weapon'?'wielded':slot)+'.</p>':''}</div>`,[]);$('modal-foot').innerHTML='';const actions=[];const act=(text,fn)=>actions.push({text,action:()=>{this.close();fn();this.refresh();}});if(slot)act('Remove',()=>g.unequip(i));else if(i.category==='weapon')act('Wield',()=>g.equip(i,'weapon'));else if(['armor','ring','amulet'].includes(i.category))act('Wear',()=>g.equip(i));if(i.category==='food')act('Eat',()=>g.eat(i));if(i.category==='potion')act('Quaff',()=>g.quaff(i));if(['scroll','spellbook'].includes(i.category))act('Read',()=>g.read(i));if(i.category==='wand')act('Zap',()=>{if(d.direction==='NODIR')g.zap(i,null);else this.askDirection('Zap in which direction?',dir=>g.zap(i,dir));});if(i.artifact)act('Invoke',()=>g.invokeArtifact(i));if(i.contents)act('Open container',()=>this.containerMenu(i));if(i.category==='tool'&&!i.contents)act('Apply',()=>this.useTool(i));if(!slot)act('Drop',()=>g.drop(i));for(let [n,a]of actions.entries()){let b=document.createElement('button');b.className=n===0?'primary-button':'secondary-button';b.textContent=a.text;b.onclick=a.action;$('modal-foot').append(b);}let back=document.createElement('button');back.className='secondary-button';back.textContent='Back';back.onclick=()=>this.inventory();$('modal-foot').append(back);}
 spells(cast){let list=this.game.player.spells;this.show(cast?'Cast a spell':'Your spellbook','ARCANA & INCANTATIONS',`<p class="modal-copy">Power ${this.game.player.pw} / ${this.game.player.maxPw}. Spells cost five power per spell level. Read spellbooks to learn new magic.</p>`+(list.map((s,i)=>{let d=N.lookup(s.name,'spellbook');return`<button class="inventory-row" data-spell="${i}"><kbd>${String.fromCharCode(97+i)}</kbd><span class="item-icon">✧</span><span class="item-name">${esc(s.name)}<span class="item-note">LEVEL ${d?.level||1} · ${esc(d?.school||'magic')} · ${Math.round(s.knowledge/20000*100)}% RETAINED</span></span><span class="item-weight">${(d?.level||1)*5} PW</span></button>`;}).join('')||'<div class="empty-state">You have not learned any spells yet.<br>Read a spellbook [r] to begin studying.</div>'),[]);const select=s=>{this.close();if(selfMagic.has(s.name)){this.game.cast(s,null);this.refresh();}else this.askDirection('Cast '+s.name+' in which direction?',d=>this.game.cast(s,d));};$('modal-body').querySelectorAll('[data-spell]').forEach(b=>b.onclick=()=>select(list[+b.dataset.spell]));this.modal.onKey=k=>{let s=list[k.charCodeAt(0)-97];if(s)select(s);};}
  attributes(){let p=this.game.player;this.show(p.name+' the '+p.rank,'CHARACTER RECORD',`<p class="modal-copy">Level ${p.level} ${p.align.toLowerCase()} ${p.race.toLowerCase()} ${p.role.toLowerCase()}.</p><div class="stats-grid">${['STRENGTH','DEXTERITY','CONSTITUTION','INTELLIGENCE','WISDOM','CHARISMA'].map((n,i)=>`<div class="stat-card"><strong>${this.game.attribute(i)}</strong><small>${n}</small></div>`).join('')}</div><p class="modal-copy">${p.properties.length?'Intrinsic properties: '+esc(p.properties.map(s=>s.replace('MR_','').toLowerCase()).join(', ')): 'No intrinsic properties.'}<br>Hunger: ${this.game.hunger} (${p.nutrition})<br>Carrying ${this.game.weight} of ${this.game.capacity} weight.<br>Conduct: ${this.game.conduct.kills} kills · ${this.game.conduct.food} meals · ${this.game.conduct.prayers} prayers.</p>`,[]);}
 discoveries(){let list=this.game.player.inventory.filter(i=>i.known||this.game.identified[i.category+':'+i.name]);this.show('Discoveries','KNOWLEDGE IS SURVIVAL',`<p class="modal-copy">Known carried objects and identified appearances persist throughout this journey.</p>${this.inventoryRows(list)}`,[]);this.wireItems(list,i=>this.itemDetail(i));}
 chronicle(){this.show('The dungeon chronicle','EVERY TURN TELLS A STORY',this.game.messages.map(m=>`<div class="modal-log ${m.type}"><span class="log-turn">${m.turn}</span>${esc(m.text)}</div>`).join(''),[]);$('modal-body').scrollTop=$('modal-body').scrollHeight;}
 map(){this.show($('location').textContent,'CARTOGRAPHY · DEPTH '+this.game.depth,'<canvas id="large-map" class="big-map" width="1200" height="420"></canvas><p class="modal-copy" style="margin:16px 0 0">Gold: you and stairways · green: companions · rust: hostile creatures.<br>Only explored terrain is recorded. Unseen monsters are not shown.</p>',[{text:'Dungeon overview',action:()=>this.overview()}]);this.drawMap($('large-map'),true);}
 overview(){this.show('Your descent','DUNGEON OVERVIEW',Object.values(this.game.levels).map(l=>`<div class="inventory-row"><span class="item-icon">${l.depth===this.game.depth&&l.branch===this.game.branch?'◇':'·'}</span><span class="item-name">${l.branch==='Mines'?'Gnomish Mines':'Dungeons of Doom'} · level ${l.depth}<span class="item-note">${l.tiles.flat().filter(t=>t.seen&&t.type==='altar').length?'ALTAR · ':''}${l.rooms.some(r=>r.shop)?'SHOP · ':''}${l.branch==='Dungeons'&&l.depth===3?'MINES ENTRANCE':''}</span></span></div>`).join(''),[]);}
 help(){const keys=[['Numpad 1–9','Move in eight directions; 5 waits'],['Arrows','Move north, south, east, west'],['Shift + numpad','Run until danger or an obstruction'],['i / d','Inventory / drop an item'],[', / :','Pick up / examine your square'],['o / c / k','Open / close / kick a door'],['Ctrl + D','Kick (also works with vi movement)'],['w / W / T','Wield / wear armor / take off armor'],['P / R','Put on / remove an accessory'],['e / q / r','Eat / quaff / read'],['a / z / Shift + Z','Apply a tool / zap wand / cast spell'],['Q / f / t','Ready quiver / fire / throw'],['s / .','Search / wait one turn'],['< / >','Use stairs up / down'],['E / #','Engrave / extended commands'],['m / F + direction','Move safely / force an attack'],['n10s','Search ten times (number_pad mode)'],['S / O','Save and suspend / options'],['Ctrl + X / Ctrl + O','Attributes / dungeon overview'],['/ / ;','Inspect a tile or creature'],['Tab / V','Expanded map / message chronicle'],['Escape','Cancel command or open pause menu']];this.show('A guide to survival','COMMAND REFERENCE',`<div class="help-intro"><div class="movement-grid">${['7 ↖','8 ↑','9 ↗','4 ←','5 ·','6 →','1 ↙','2 ↓','3 ↘'].map(k=>'<kbd>'+k+'</kbd>').join('')}</div><p>The dungeon moves when you do.<br>Walk into a hostile creature to attack.<br>Inventory letters select items. Escape cancels a pending action.</p></div><table class="key-table">${keys.map(([k,v])=>`<tr><td><kbd>${k}</kbd></td><td>${v}</td></tr>`).join('')}</table><p class="modal-copy" style="margin-top:20px">Default: number_pad enabled. In Options, choose vi movement to use y u h j k l b n. Lower armor class is better. Food, safe positioning, and your pet are essential.</p>`,[{text:'About this edition',action:()=>this.about()},{text:'Return to the dungeon',action:()=>this.close()}]);}
 options(){this.show('Make yourself at home','OPTIONS',`<div class="option-row"><label for="opt-num">Movement layout<small>Numpad physical keys work with Num Lock on or off.</small></label><select id="opt-num"><option value="pad" ${this.numberPad?'selected':''}>Number pad</option><option value="vi" ${!this.numberPad?'selected':''}>Classic vi keys</option></select></div><div class="option-row"><label for="opt-door">Auto-open doors<small>Walk into an unlocked door to open it and continue through.</small></label><input id="opt-door" type="checkbox" ${this.game.autoOpenDoors?'checked':''}></div><div class="option-row"><label for="opt-pick">Autopickup gold<small>Other items use the comma command.</small></label><input id="opt-pick" type="checkbox" ${this.game.autopickup?'checked':''}></div><div class="option-row"><label for="opt-audio">Procedural sound<small>Dungeon ambience and synthesized effects.</small></label><input id="opt-audio" type="checkbox" ${this.audio.enabled?'checked':''}></div><div class="option-row"><label for="opt-quality">Render quality<small>Economy reduces resolution and disables shadows.</small></label><select id="opt-quality"><option value="high" ${this.renderer.quality==='high'?'selected':''}>High · shadows</option><option value="low" ${this.renderer.quality==='low'?'selected':''}>Economy</option></select></div>`,[{text:'Done',action:()=>this.close()},{text:'Controls',action:()=>this.help()}]);$('opt-num').onchange=e=>this.numberPad=e.target.value==='pad';$('opt-door').onchange=e=>this.game.autoOpenDoors=e.target.checked;$('opt-pick').onchange=e=>this.game.autopickup=e.target.checked;$('opt-audio').onchange=()=>{this.audio.start();this.audio.toggle();};$('opt-quality').onchange=e=>this.renderer.setQuality(e.target.value);}
 textPrompt(title,eyebrow,label,value,fn,suggestions=[]){this.show(title,eyebrow,`<form id="text-form"><div class="form-row"><label for="text-entry">${esc(label)}</label><input id="text-entry" maxlength="80" value="${esc(value)}" autocomplete="off" spellcheck="false"></div><button class="primary-button" type="submit">Continue ↵</button></form>${suggestions.length?'<div class="command-suggestions">'+suggestions.map(s=>`<button data-text="${esc(s)}">#${esc(s)}</button>`).join('')+'</div>':''}`,[]);$('text-form').onsubmit=e=>{e.preventDefault();let text=$('text-entry').value.trim();if(!text)return;this.close();fn(text);};$('modal-body').querySelectorAll('[data-text]').forEach(b=>b.onclick=()=>{this.close();fn(b.dataset.text);});}
 extended(){const commands=['invoke','pray','loot','offer','sit','chat','untrap','dip','name','overview','conduct','quit'];this.textPrompt('An extended command','THE OLD WAYS','# command','',name=>this.extendedCommand(name.toLowerCase().replace(/^#/,'')),commands);}
 extendedCommand(name){let g=this.game;switch(name){case'invoke':this.selectItem('Invoke an artifact',i=>!!i.artifact,i=>g.invokeArtifact(i));return;case'pray':this.show('Call upon your god','PRAYER',`<p class="modal-copy">Pray for aid? Calling too often can anger your deity.</p>`,[{text:'Pray [y]',action:()=>{this.close();g.pray();this.refresh();}},{text:'Cancel [n]',action:()=>this.close()}]);this.modal.onKey=k=>{if(k==='y')$('modal-foot').children[0].click();if(k==='n')this.close();};return;case'overview':this.overview();return;case'conduct':this.attributes();return;case'quit':this.pause();return;
  case'loot':{const o=g.level.items.find(o=>N.distance(o,g.player)===0&&g.def(o.item).container);if(o)this.containerMenu(o.item);else this.selectItem('Open a container',i=>!!i.contents,i=>this.containerMenu(i));return;}
  case'sit':{const t=g.tile(g.player.x,g.player.y);if(t.type==='throne'){g.log('You sit on the opulent throne.');if(g.rng.next()<.2){g.player.hp=g.player.maxHp;g.log('You feel much better.','good');}else g.log('You feel somehow out of place.');}else g.log('You sit down on the hard floor.');g.endTurn();break;}
  case'offer':if(g.tile(g.player.x,g.player.y).type!=='altar'){g.log('There is no altar here.');break;}this.selectItem('Offer a sacrifice',i=>!!i.corpse||i.name==='Amulet of Yendor',i=>g.offer(i));return;
  case'chat':g.chat();break;
  case'untrap':this.askDirection('Disarm a trap in which direction?',([dx,dy])=>{let t=g.level.traps.find(t=>t.x===g.player.x+dx&&t.y===g.player.y+dy&&t.seen);if(!t)g.log('You find no trap there.');else if(g.rng.int(1,20)<g.player.stats[1]){g.level.traps=g.level.traps.filter(j=>j!==t);g.log('You disarm the trap.','good');g.endTurn();}else{g.log('You fail to disarm the trap.');g.endTurn();}});return;
  case'dip':this.selectItem('Dip an item',()=>true,i=>{if(g.tile(g.player.x,g.player.y).type==='fountain'){g.dip(i);this.refresh();}else this.selectItem('Dip into water',j=>j.category==='potion'&&j.name==='water'&&j!==i,water=>g.dip(i,water));});return;
  case'name':this.selectItem('Name an object',()=>true,i=>this.textPrompt('Give it a name','NAME OBJECT','Name',i.named||'',text=>{i.named=text;this.refresh();}));return;
  default:g.log(`The extended command #${name} is not implemented. Press ? for supported controls.`,'warning');break;}this.refresh();}
 wish(){this.textPrompt('Make a wish','A RARE OPPORTUNITY','An object name (for example: blessed +2 long sword)','',text=>{let name=text.replace(/^(blessed|cursed|uncursed)\s+/,'').replace(/^[+-]\d+\s+/,'');let d=N.ITEMS.find(i=>i.name.toLowerCase()===name.toLowerCase())||N.ITEMS.find(i=>(i.category+' of '+i.name).toLowerCase()===name.toLowerCase());if(d&&!['Amulet of Yendor','Bell of Opening','Candelabrum of Invocation','Book of the Dead'].includes(d.name)){let item=this.game.createItem(d.name,d.category,{buc:text.startsWith('blessed')?1:text.startsWith('cursed')?-1:0,enchant:Math.min(3,Number(text.match(/[+-]\d+/)?.[0]||0)),known:true,bucKnown:true});if(!this.game.addItem(item))this.game.level.items.push({x:this.game.player.x,y:this.game.player.y,item});this.game.log('Your wish is granted.','good');}else this.game.log('Nothing fitting that description comes to mind.');this.refresh();});}
 genocide(){this.textPrompt('Name a species','GENOCIDE','Which monster do you wish to erase?','',name=>{let d=N.monsterDef(name.toLowerCase());if(!d||d.generation.includes('G_UNIQ')||!d.generation.includes('G_GENO'))this.game.log('That species cannot be genocided.');else{this.game.genocided.push(d.name);for(let l of Object.values(this.game.levels))l.monsters=l.monsters.filter(m=>m.kind!==d.name);this.game.log(`All ${d.name}s are wiped out.`, 'warning');}this.refresh();});}
 isNoticeable(){const g=this.game,p=g.player,t=g.tile(p.x,p.y);if(g.level.items.some(o=>o.x===p.x&&o.y===p.y))return true;if(['door','openDoor','up','down','branch','fountain','altar','grave','sink','throne'].includes(t?.type))return true;return g.level.monsters.some(m=>m.hp>0&&!m.tame&&!m.peaceful&&g.tile(m.x,m.y)?.visible);}
 run(dir,safe=false,untilNotice=false){if(!this.canAct())return;this.runTimer=setInterval(()=>{if(this.modal||this.suspended){this.stopRun();return;}if(this.game.level.monsters.some(m=>!m.tame&&!m.peaceful&&this.game.tile(m.x,m.y)?.visible)){this.stopRun();this.toast('Travel interrupted: a hostile creature is in sight.');return;}let ok=this.game.move(...dir,safe?'safe':'normal');this.refresh();const tile=this.game.tile(this.game.player.x,this.game.player.y);if(!ok||this.game.dead||(untilNotice?this.isNoticeable():tile?.type!=='corridor'))this.stopRun();},125);}
 repeatAction(key,count){let left=Math.min(999,count);this.runTimer=setInterval(()=>{if(!this.canAct()||--left<0){this.stopRun();return;}if(this.game.level.monsters.some(m=>!m.tame&&!m.peaceful&&N.distance(m,this.game.player)<3)){this.stopRun();this.toast('Repeated action interrupted by danger.');return;}if(key==='s')this.game.search();else this.game.wait();this.refresh();},80);}
 stopRun(){if(this.runTimer){clearInterval(this.runTimer);this.runTimer=null;}}
 travel(target){const g=this.game,p=g.player;if(!g.passable(target.x,target.y)){this.toast('That square is blocked.');return;}let queue=[{x:p.x,y:p.y,path:[]}],seen=new Set([p.x+','+p.y]),found=null;for(let i=0;i<queue.length&&i<1680;i++){let cur=queue[i];if(N.distance(cur,target)===0){found=cur.path;break;}for(let d of N.DIRS){let x=cur.x+d[0],y=cur.y+d[1],k=x+','+y,t=g.tile(x,y);if(seen.has(k)||!t?.seen||!g.passable(x,y)||['water','lava'].includes(t.type))continue;if(d[0]&&d[1]&&(['openDoor','door'].includes(t.type)||['openDoor','door'].includes(g.tile(cur.x,cur.y).type)||!g.passable(cur.x+d[0],cur.y)&&!g.passable(cur.x,cur.y+d[1])))continue;seen.add(k);queue.push({x,y,path:[...cur.path,d]});}}
  if(!found){this.toast('No known open path. Open doors or explore to find a route.');return;}this.stopRun();this.runTimer=setInterval(()=>{if(this.modal||g.dead||!found.length){this.stopRun();return;}if(g.level.monsters.some(m=>!m.tame&&!m.peaceful&&g.tile(m.x,m.y)?.visible)){this.stopRun();this.toast('Travel interrupted by a hostile creature.');return;}if(!this.canAct())return;let d=found.shift(),ok=g.move(...d,'safe');this.refresh();if(!ok)this.stopRun();},125);}
 save(){if(this.game.dead||this.game.won){this.toast('This journey has ended.');return;}try{localStorage.setItem('nethack3d-save',this.game.serialize());this.pause(true);this.suspended=true;}catch{this.toast('Local storage is unavailable. Use Export save from the pause menu.');}}
 restore(recovery=false){try{const key=recovery?'nethack3d-recovery':'nethack3d-save',text=localStorage.getItem(key);if(!text){this.toast('No saved journey was found.');return;}this.game=N.Game.restore(text);localStorage.removeItem(key);this.suspended=false;this.ended=false;this.close();this.renderer.game=this.game;this.renderer.buildLevel();this.renderer.focus.set(this.game.player.x,0,this.game.player.y);this.game.log('Your journey continues.','story');this.refresh();}catch(e){this.toast('Cannot restore this save: '+e.message);}}
 pause(saved=false){this.cancel();let hasSave=false,hasRecovery=false;try{hasSave=!!localStorage.getItem('nethack3d-save');hasRecovery=!!localStorage.getItem('nethack3d-recovery');}catch{}this.show(saved?'Your journey is safe':'A moment of respite',saved?'SAVED & SUSPENDED':'THE DUNGEON CAN WAIT',`<p class="modal-copy">${saved?'Your game has been saved on this browser. You can close the window and return later.':'Take a breath. The dungeon remains still until your next action.'}</p><div class="item-actions"><button id="export-save">Export save file</button><button id="import-save">Import save file</button><input id="save-file" type="file" accept=".json" hidden></div>`,[{text:saved?'Resume saved journey':'Return to the dungeon',action:()=>{if(saved)this.restore();else this.close();}},{text:'New journey',action:()=>this.newGameMenu()},...(hasSave&&!saved?[{text:'Restore saved game',action:()=>this.restore()}]:[]),...(hasRecovery&&!saved?[{text:'Recover last session',action:()=>this.restore(true)}]:[])]);$('export-save').onclick=()=>{const blob=new Blob([this.game.serialize()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='nethack-'+this.game.seed+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import-save').onclick=()=>$('save-file').click();$('save-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{let game=N.Game.restore(await file.text());this.game=game;this.suspended=false;this.ended=false;this.close();this.renderer.game=game;this.renderer.buildLevel();this.renderer.focus.set(game.player.x,0,game.player.y);this.refresh();}catch(err){this.toast('Invalid save: '+err.message);}};}
 newGameMenu(){let selected='Knight';this.show('Enter the Mazes of Menace','A NEW JOURNEY',`<p class="modal-copy">Seek the Amulet of Yendor in the depths below. Every journey begins with a name, a calling, and a little courage.</p><div class="form-grid"><div class="form-row"><label for="new-name">YOUR NAME</label><input id="new-name" value="Adventurer" maxlength="24" autocomplete="off"></div><div class="form-row"><label for="new-seed">DUNGEON SEED</label><input id="new-seed" value="${Math.random().toString(36).slice(2,10).toUpperCase()}" maxlength="40" autocomplete="off"></div></div><div class="role-grid">${Object.keys(N.roles).map(r=>`<button class="role-choice ${r===selected?'selected':''}" data-role="${r}">${r}</button>`).join('')}</div><div id="role-description" class="role-description"></div><p class="modal-copy" style="font-size:10px;margin-bottom:0">This edition currently starts human characters. Creating a new journey replaces your active run; exported and suspended saves remain available.</p>`,[{text:'Begin the descent →',action:()=>{this.game=new N.Game($('new-seed').value||'YENDOR',selected,$('new-name').value||'Adventurer');this.suspended=false;this.ended=false;this.cancel();this.close();this.renderer.game=this.game;this.renderer.buildLevel();this.renderer.focus.set(this.game.player.x,0,this.game.player.y);this.refresh();}},{text:'Back',action:()=>this.suspended?this.pause(true):this.close()}]);const update=()=>{const r=N.roles[selected];$('role-description').innerHTML=`<strong>${selected}</strong> · ${r.align} · ${r.hp} HP · ${r.pw} Power<br>${r.spells?.length?'Begins with '+r.spells.join(' and ')+'.':'Begins with '+r.gear.slice(0,3).map(i=>i[0]).join(', ')+'.'} ${r.props?.length?'Natural abilities: '+r.props.map(p=>p.replace('MR_','').toLowerCase()).join(', ')+'.':''}`;};$('modal-body').querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{selected=b.dataset.role;$('modal-body').querySelectorAll('[data-role]').forEach(b=>b.classList.toggle('selected',b.dataset.role===selected));update();});update();}
 endScreen(){this.show(this.game.won?'You return from the depths':'Here lies '+this.game.player.name,this.game.won?'THE AMULET IS YOURS':'THE END OF A JOURNEY',`<div class="death-symbol">${this.game.won?'♜':'†'}</div><p class="modal-copy" style="text-align:center">${this.game.won?'You offer the Amulet on the Astral Plane and ascend to demigodhood.':esc('Killed by '+this.game.deathCause+'.')}<br>${esc(this.game.player.name)} the ${esc(this.game.player.role.toLowerCase())} reached dungeon level ${this.game.depth}.</p><div class="stats-grid"><div class="stat-card"><strong>${this.game.turn}</strong><small>TURNS SURVIVED</small></div><div class="stat-card"><strong>${this.game.conduct.kills}</strong><small>MONSTERS SLAIN</small></div><div class="stat-card"><strong>${this.game.player.gold}</strong><small>GOLD COLLECTED</small></div></div>`,[{text:'Begin another journey',action:()=>this.newGameMenu()},{text:'Read the chronicle',action:()=>this.chronicle()}]);try{localStorage.removeItem('nethack3d-recovery');}catch{}}
 about(){this.show('An old dungeon. A new dimension.','NETHACK 3D · LOCAL EDITION',`<p class="modal-copy">A procedural Three.js interpretation of NetHack 3.6.6. Every mesh, texture, animation, and sound is generated in code. No external art, recordings, frameworks, or online services are used.</p><p class="modal-copy">The content catalog is derived from the official NetHack 3.6.6 monster and object source tables. The JavaScript engine is an independent implementation: this is a playable adaptation, not a complete or exact port.</p><p class="modal-copy">Implemented: room-and-corridor exploration, eight-way turn-based movement, pets, combat, hunger, inventory, equipment, unidentified appearances, curses, traps, many magic effects, shops, a Mines branch, persistent levels, and save/restore.</p><p class="modal-copy">Still incomplete: exact generation and probability tables, all special monster and object interactions, all races, quests and special levels, Sokoban, Gehennom rituals, the elemental planes, and true ascension. The current end condition is returning with the Amulet from depth 30.</p><p class="modal-copy"><a class="source-link" href="https://www.nethack.org/v366/Guidebook.html" target="_blank" rel="noopener">NetHack 3.6.6 Guidebook ↗</a><br><a class="source-link" href="https://github.com/NetHack/NetHack/tree/NetHack-3.6.6_Released" target="_blank" rel="noopener">Official release source ↗</a><br><a class="source-link" href="reference/NetHack-LICENSE.txt" target="_blank">NetHack General Public License ↗</a></p>`,[]);}
}
N.installMenus(UI);
try{window.app=new UI();}catch(error){console.error(error);$('modal-backdrop').hidden=false;$('modal-title').textContent='The dungeon could not awaken';$('modal-eyebrow').textContent='STARTUP ERROR';$('modal-body').innerHTML=`<p class="modal-copy">${esc(error.message)}</p><p class="modal-copy">This game needs a browser with WebGL enabled. Open index.html in a current desktop browser and enable hardware acceleration.</p>`;}
})();
